### ISSUE TITLE
Facing issue when redirecting back on the app route from the different server

### ISSUE THREAD

**Issue by asada-chetu** [Kyon147/laravel-shopify#100]
### Discussed in https://github.com/Kyon147/laravel-shopify/discussions/99

<div type='discussions-op-text'>

<sup>Originally posted by **asada-chetu** February 22, 2023</sup>
Facing issues when redirecting back on the app route from a different server. we are opening a third-party page in the embedded app iframe after completing the process. we want to redirect back to the specific route with the host but show the blank page in the embedded app iframe. Please guide me what's the issue.

   
![image](https://user-images.githubusercontent.com/102379477/220431891-8e621e3d-9af0-43ac-b82f-c2e895326689.png)
</div>

**Comment by Kyon147** [comment]
Not an app issue so closing as you also have a dissuasion open which is more appropriate.

**Comment by asada-chetu** [comment]
Hi @Kyon147
Actually, we are facing an issue in the app bridge, when we redirect back from the other server. We are getting some random string in the host. And same method is when we have turned back the same server but a different domain and then get the store URL in the host. 

![image](https://user-images.githubusercontent.com/102379477/221587646-1dc01bfb-20ae-4b22-a9e9-2589c4ad6de5.png)
![image](https://user-images.githubusercontent.com/102379477/221587300-de7f1646-0f61-4dfe-b83c-bb5ba7808057.png)
![image](https://user-images.githubusercontent.com/102379477/221587431-df577c0a-ca9e-4b14-8338-8b1a4d61acbe.png)

So, how can we direct back to the same iframe from a different server?
