### ISSUE TITLE
Mixed Content: The page at 'https://admin.shopify.com/store/bspdev/apps/1f01de194656cc37c66725b7e12eeef0/authenticate/token?shop=bspdev.myshopify.com&target=%2F%3Fhost%. This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by faisalaltaf** [Kyon147/laravel-shopify#104]
p*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

Please describe the current behavior?

## Failure Information

Please help provide information about the failure if this is a bug.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
2. Step 2
3. ...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: vX.Y.Z
* Laravel Version: vX.Y.Z
* PHP Version: vX.Y.Z
* Template Engine: Blade or React
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by faisalaltaf** [comment]
please check my issue help me

**Comment by faisalaltaf** [comment]
please help me

**Comment by enmaboya** [comment]
this problem has nothing to do with this package.

simply add to the AppServiceProvider

URL::forceScheme('https')

**Comment by f4llenz** [comment]
It's literally in the docs https://github.com/Kyon147/laravel-shopify/wiki/ngrok

**Comment by Kyon147** [comment]
@enmaboya is right, this is not a package issue but you are serving mixed content over http and https.
