### ISSUE TITLE
Session Token Is Invalid

### ISSUE THREAD

**Issue by auspicious-soft** [Kyon147/laravel-shopify#105]
I have installed the app. Its installed successfully. But when I have execute the API's it gives the error Session Token Is Invalid. API did not execute any code due to this error.

![Screenshot_1](https://user-images.githubusercontent.com/60027228/223053216-94a84add-43f2-4e77-946d-faa5010b491d.png)

**Comment by Kyon147** [comment]
Please provide more information on what version you are using, are you using blade templates etc 

There's not enough information to be able to see what the issue could be at the moment.

Thanks!

**Comment by auspicious-soft** [comment]
Laravel Version: 7.1
Osiset Version: 17.1

I am using the laravel blade file.
