### ISSUE TITLE
Project loading in Shopify admin panel but not when accessing URL

### ISSUE THREAD

**Issue by Lauren076** [Kyon147/laravel-shopify#109]
Hi Guys,

I installed the laravel-shopify package through composer and got every up and running. Also installed the app in Shopify and it's working there like a charm:

![Schermafbeelding 2023-03-09 om 21 56 44](https://user-images.githubusercontent.com/2550558/224155998-2270224d-70e8-43a0-a0c5-0dcd8b1126e2.png)

But when I want to access the site through the public URL: https://rephonenl.shopify.com/a/inruilen/ I get redirected and there is data missing in the url (undefined in the URL).

![Schermafbeelding 2023-03-09 om 22 18 40](https://user-images.githubusercontent.com/2550558/224162146-bd89492f-ed0d-494d-9b52-acbc601a0e62.png)

**URL example**
`https://undefined/admin/apps/xxxxx/authenticate/token?shop=rephonenl.myshopify.com&target=%2F%3Fpath_prefix%3D%252Fa%252Finruilen%26signature%xxxxx`

If I dd() the $request parameter on line 107 in AuthController Trait I get the following responses:

**From Shopify dashboard**
![Schermafbeelding 2023-03-09 om 22 13 59](https://user-images.githubusercontent.com/2550558/224160913-aa4d54b5-d044-4544-86af-aa04bd617bd1.png)

**From direct accessing URL**
![Schermafbeelding 2023-03-09 om 22 14 25](https://user-images.githubusercontent.com/2550558/224161285-e978bb47-32d9-40cb-b39f-11964991a561.png)

I am using the latest version of the project (17.4.4) and I am using Laravel 7.30.6

If you can help me that would be great. I don't know where to start.

**Comment by Kyon147** [comment]
The package only supports embedded mode at the moment, there is no way to access the app outside of the Shopify admin. 

Going to close this issue for now.

**Comment by Lauren076** [comment]
So if there is no way to access the app outside of the Shopify admin, then what is the purpose? 

The documentation is stating this: "App proxies are way for your app to display content directly inside a shop with it's own URL (like http://cool-shop.com/apps/cool-app)."

URL: https://github.com/Kyon147/laravel-shopify/wiki/App-Proxies

So you are telling me, the package is only capable to access the other app if you are logged into the Shopify admin and not when a visitor visits the site?

**Comment by Kyon147** [comment]
That wiki entry might be a little bit misleading by the way it is worded. Here's the description from Shopify: 

> App proxies take requests to Shopify links, and redirect them to external links. This allows you to fetch and display data on a merchant's store from an external source.

You can proxy part of your app, to return data and the proxy handles the issues you face around CORS etc, it also allowed you to return a liquid page as HTML. This is useful if you want to do custom pages that your app controls.

It's not designed to load your full app on the storefront. You can only access the "admin" side of the app, in the Shopify admin - if you want to use the app proxy you have to set up the proxy requests outlined here https://shopify.dev/docs/apps/online-store/app-proxies but as mentioned there are limitations.

**Comment by shinyatentree** [comment]
Currently I am working on the app proxy on the laravel side I should be able to set up middle ware and it supposed to work automatically? like the following
`Route::middleware('shopify.auth')->group(function () {
    Route::get('/api/products', [ProductController::class, 'get']);
});`

**Comment by shinyatentree** [comment]
shopify one. I assume they must be very similar

**Comment by shinyatentree** [comment]
ok I can set up my app to work with this library instead. As you mentioned if I want to set up proxy at /api/top-products on laravel side I should be setting up with auth.proxy? If so is there any sample to get session using Client ID and secret on server side on Laravel?

**Comment by shinyatentree** [comment]
Do you happen to now how I can get storefront-public-access-token when calling url on laravel from appProxy?
