### ISSUE TITLE
Not redirecting to billing package  v18

### ISSUE THREAD

**Issue by slashcart** [Kyon147/laravel-shopify#121]
## Expected Behavior

User should be redirected to billing

## Current Behavior

It keeps showing skeleton

I am using tokenRoute for billing redirection as shown in image below
![image](https://user-images.githubusercontent.com/113967682/226261630-da091674-f9ee-4eb0-a3b2-b8a755e38e92.png)

### Context

* Package Version: 18
* Laravel Version: 10
* PHP Version: 8.1
* Template Engine: Blade

**Comment by zeeshanhaider6236dev** [comment]
We are facing same issue 

@Kyon147 can you please solve this one

**Comment by alimud1** [comment]
Anyone Solve this issue ?

**Comment by zeeshanhaider6236dev** [comment]
@alimud1 not yet we are waiting for Kyon

**Comment by alimud1** [comment]
🥺🥺🥺

**Comment by Kyon147** [comment]
@slashcart you are not passing `shop` as part of the redirect for billing.

**Comment by slashcart** [comment]
I tried this

**Comment by Kyon147** [comment]
@slashcart do you see any errors in the console or php errors?

If you are seeing the skeleton loading page, it usually means you are not init app bridge properly i.e. missing host value.

**Comment by slashcart** [comment]
I am looking more deeply in it i will let you when i will figure out the problem

**Comment by Kyon147** [comment]
@slashcart great that you fixed it. Could you put what your issue was and the solution, that way other people can use it if they run into this issue too.
