### ISSUE TITLE
Error dispatch job in laravel 10 - Call to undefined method dispatchNow()

### ISSUE THREAD

**Issue by nonghinh** [Kyon147/laravel-shopify#125]
In Laravel 10.x, the **dispathNow** method has been replaced by the **dispatchSync** method. Please update the package to remove the error "Call to undefined methodApp\Jobs\AfterAuthorizeJob::dispatchNow()".
The error only occurs when I configure the execution of jobs with "[inline => true]"

**Comment by Kyon147** [comment]
There is already a PR for it #124 - feel free to give that branch a test.

**Comment by Kyon147** [comment]
I've created a new release which should fix this issue https://github.com/Kyon147/laravel-shopify/releases/tag/v18.0.1

**Comment by nonghinh** [comment]
Thank you @Kyon147

**Comment by Kyon147** [comment]
@nonghinh no problem, can you close the ticket once resolved.
