### ISSUE TITLE
App billing screen did not open on reinstall.

### ISSUE THREAD

**Issue by DevStackRahul** [Kyon147/laravel-shopify#136]
I have using the app package 17.5 and php 7.4. I have using the recurring billing for my app. When I install the app first time on the store it display the billing screen for approval but on reinstall the app billing screen not open and app install directly.

I want to open the billing screen on app reinstall also.

Kindly help me to resolve this issue.

**Comment by Kyon147** [comment]
@DevStackRahul are you making sure that the uninstall job is running correctly? I.e `plan_id` is set to `null` as if it is not then you won't get the billing screen.

**Comment by DevStackRahul** [comment]
@Kyon147 on uninstall the app the date added in deleted_at column but plan id did not make null.

**Comment by DevStackRahul** [comment]
Ok. I have placed the code to made the plan_id null in app uninstall job.

Thanks
