### ISSUE TITLE
Bug! After app installation i redirect to the wrong url which actually cause the empty screen.

### ISSUE THREAD

**Issue by haseebtanveerbutt** [Kyon147/laravel-shopify#139]
After redirect authentication of app i am redirecting to this url. This url will work fine i will remove "admin/" from that url. Before 2 days it was working fine. But now it is not working. Nothing error is display, it shows me empty screen. I just redirected to that below link. This link wokring fine if i will remove the "admin/" from url. 
Can any buddy tell me who i can fix it. 
https://admin.shopify.com/store/spy-blocker-testing/admin/apps/0c6785ee8ac93474f133c0df1c8233b8/authenticate/token?shop=admin.shopify.com%2Fstore%2Fspy-blocker-testing&target=%2F

I am using:
Laravel 7.29
"osiset/laravel-shopify": "^17.3.2"
php: ^7.2.5|^8.0

![image](https://user-images.githubusercontent.com/61355150/230883949-16e6667b-27b9-4637-b75a-9cf469bb12c7.png)

It's Urgent. 
Thank You

**Comment by Kyon147** [comment]
@haseebtanveerbutt it looks like `shop` param is incorrect for some reason - this should be the `myshopify.com` domain not the admin one.

**Comment by Kyon147** [comment]
@haseebtanveerbutt are you still finding this issue after upgrading?

**Comment by haseebbutt1999** [comment]
@Kyon147 i not check yet by upgrading it to 17.3.2 to 17.5 i will check it.

**Comment by Kyon147** [comment]
Going to close this ticket for now, please re-open if the issue persists.
