### ISSUE TITLE
Uninstall webhook ovenwork

### ISSUE THREAD

**Issue by YunAltinus** [Kyon147/laravel-shopify#152]
Uninstall webhook overworks when app is loaded

## Expected Behavior

Uninstall webhook not work when app is loaded

## Current Behavior

Im using supervisor and laravel/horizon. I leave the image below

## Failure Information
![image](https://user-images.githubusercontent.com/62405204/236629263-57ae6c5f-469a-4b6a-b01b-91c3084dd814.png)

![image](https://user-images.githubusercontent.com/62405204/236629672-7f0aa5ba-4b1e-44a4-985c-7f2c78ab29f3.png)

### Context

* Package Version: v18.0.1
* Laravel Version: v9.52.7
* PHP Version: v8.1.18
* Template Engine: webpack - vue
* Using a toolset Docker

**Comment by Kyon147** [comment]
Testing webhooks locally is very inconsistent, I'd suggest trying to test your app on an actual server or use something like ngrok (as that usually works)

**Comment by YunAltinus** [comment]
Actually the app is already running on ngrok. Other webhook works fine but Uninstall webhook ovenwork. Are we sure there is no problem?

**Comment by Kyon147** [comment]
@YunAltinus i've not seen any failures on any of my live apps to suggest there is an issue. If you can do some more digging and provide more information we might be able to look further.
