### ISSUE TITLE
When I reinstall my extension, it gives error

### ISSUE THREAD

**Issue by racibaz** [Kyon147/laravel-shopify#157]
When I reinstall my extension, it gives error. If I delete exist shop (user) manually, it works.
 
## Expected Behavior
When I reinstall my extension, it gives error. If I delete exist shop (user) manually, it works.

## Failure Information
![Screen Shot 2023-05-11 at 12 04 19](https://github.com/Kyon147/laravel-shopify/assets/1975129/3122034a-38ba-4fe6-a616-8c03ea753f9b)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

### Context

* Package Version: v18.0
* Laravel Version: v9.19
* PHP Version: v8.1
* Template Engine: Blade
* Using a toolset : Laravel Sail (Docker)

**Comment by racibaz** [comment]
I find the problem that I hadn't used uninstall webhook which would check the user's deleted_at field so I added to uninstall webhook to shopify endpoint and edit the my app config (shopify-app.php). It's working now.

**Comment by Kyon147** [comment]
Looks like you found the issue being the uninstall webhook not being set up, so going to close this 👍

**Comment by bretto36** [comment]
For anyone else also getting this error, i had to update to that latest version of this package as well before it would work. was on 18.0 -> 18.2 worked.
