### ISSUE TITLE
Page is not redirect back 

### ISSUE THREAD

**Issue by a-akashsoni** [Kyon147/laravel-shopify#158]
After install the shopify package in Laravel, I have made the code for update the entry. After update the entry , page is not redirect back to home page, it looks like **https://prnt.sc/TM1fxNvBfeQo**. 

Kindly give your reference as soon as possible.

Thanks

**Comment by SachinBahukhandi** [comment]
> After install the shopify package in Laravel, I have made the code for update the entry. After update the entry , page is not redirect back to home page, it looks like **https://prnt.sc/TM1fxNvBfeQo**.
> 
> Kindly give your reference as soon as possible.
> 
> Thanks

Could you please add a minimum reproducible example?

**Comment by Kyon147** [comment]
@a-akashsoni if you are using blade templates, then you need to make sure you pass your `host` param on every request including the redirect back to the homepage.

Closing this ticket, but reopen if that does not solve the issue.

**Comment by a-akashsoni** [comment]
@Kyon147 kindly help me, how to pass the param on every request including to redirect back to the homepage.
Kindly revert asap , so I can solve the issue.
Thanks

**Comment by a-akashsoni** [comment]
@Kyon147 , I have  use the same code with osiset shopify package and in that package all things are working fine. But When I installed kyon147 package on new server , same code is not working in kyon shopify package. Can you tell me why this issue has been created.

**Comment by Kyon147** [comment]
@a-akashsoni everything you need is likely in the wiki, please read it. To get you started, look at this https://github.com/Kyon147/laravel-shopify/wiki/Authentication-Process#non-spa

If you need specific coding help, please open a discussion or join the Discord. It sounds like a code issue not a package one, creating issues is only for package bugs.
