### ISSUE TITLE
Hashed Passwords - Improve documentation for Laravel 10

### ISSUE THREAD

**Issue by jeroendelau** [Kyon147/laravel-shopify#163]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

The documentation should mention that, as of Laravel 10, passwords are hashed using casts by default.
You need to disable this in order for tokens to be saved and used.
If you do not do this, the Shopify token is hashed and become unusable.

```php
 /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        //'password' => 'hashed',
    ];
```

## Current Behavior
If you try to use the API offline you will see:
`"{"errors":"[API] Invalid API key or access token (unrecognized login or wrong password)"}`

### Steps to Reproduce

1. Fresh install of laravel (10) + kyon147/laravel-shopify
2. Setup an app and Shopify App
3. Install the app on a test store
4. Observe that password in users table is hashed

### Context

* Package Version: v18.1
* Laravel Version: v10.10
* PHP Version: v8.2

**Comment by Kyon147** [comment]
@jeroendelau good catch, I'll add this to the wiki 👍
