### ISSUE TITLE
Osiset/basic-shopify-api is now abandoned

### ISSUE THREAD

**Issue by folivei** [Kyon147/laravel-shopify#166]
Thanks for the great Shopify Api for Laravel!

Composer states:
Package osiset/basic-shopify-api is abandoned, you should avoid using it. Use https://github.com/gnikyt/Basic-Shopify-API instead.

Any plan to eliminate this dependency in future?

**Comment by Kyon147** [comment]
@folivei the api just moved namespace and needs to be updated. Would be a good first PR for someone to do.

**Comment by SachinBahukhandi** [comment]
@Kyon147 I have raised a PR for the same.

**Comment by Kyon147** [comment]
`v19.0.0` now fixes this issue.
