### ISSUE TITLE
Proxy middleware returns auth user null

### ISSUE THREAD

**Issue by maazahmadkhan1** [Kyon147/laravel-shopify#17]
I am implementing proxy with latest version of osiset with laravel. I am getting Auth User null on route setuped for proxy auth proxy middleware is attached.
It should return logged in shop data

**Comment by Kyon147** [comment]
Hi @maazahmadkhan1 

I'll need more information on this bug, can you supply me with an example snippet of the code.

Also, what specific version of Laravel are you using, what version of this package and are you using SPA or Blade template.

**Comment by maazahmadkhan1** [comment]
Hi @Kyon147 thanks for your reply. I don't know what was the issue may be something was wrong with session or cache but it working now. It works when I checked next day without any change

Thanks Again
