### ISSUE TITLE
Not seeing `script_tags` on my store front

### ISSUE THREAD

**Issue by bilogic** [Kyon147/laravel-shopify#174]
1. My app is accessible on the shopify backend and I'm trying to add a script to the frontend
2. Followed the wiki to configure the `scripttags`, also added the `write_script_tags` to `api_scopes`
3. But I still don't get the script added to my frontend
4. I see `ScriptTags Job` in the wiki, why is it a job? 
5. My `jobs` table is empty, when and how does it get inserted into the table? Or is my understanding incorrect?

**Comment by Kyon147** [comment]
As of the new Online Store 2.0, you should avoid using script tags anyways. You should be using app blocks or embed blocks instead as they are backwards compatible. 

![image](https://github.com/Kyon147/laravel-shopify/assets/32519106/d6720ed4-1d64-44e7-9180-621da4509cc1)

**Comment by bilogic** [comment]
Yea thanks, I managed to solve it and utlized app embeds.
