### ISSUE TITLE
Verify theme support

### ISSUE THREAD

**Issue by rvibit** [Kyon147/laravel-shopify#18]
Any plan to merge this PR ? 

https://github.com/gnikyt/laravel-shopify/pull/1198

**Comment by Kyon147** [comment]
I can look to merge it in but it would need to be remade again on this repo.

If someone creates the PR again, I will take a look at it 👍

**Comment by joeelia** [comment]
Just a note that this is only applicable for already listed apps. Any new apps will be required to only use App Extensions
https://shopify.dev/apps/online-store/theme-app-extensions/update#migrate-your-apps

<img width="753" alt="Screen Shot 2023-01-26 at 3 19 08 PM" src="https://user-images.githubusercontent.com/44442621/214972249-49d8221b-f525-4cf4-b27f-a38cda568cdd.png">

**Comment by Kyon147** [comment]
`v19.0.0` now solves this issue.
