### ISSUE TITLE
`WebhookInstaller` job not queued after `AuthenticateShop` is executed

### ISSUE THREAD

**Issue by bilogic** [Kyon147/laravel-shopify#180]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

I followed the wiki installation, my shopify app works, I expected webhooks to also get installed

## Current Behavior

My shopify app fails to uninstall properly, after investigation, webhooks were not installed/registered in shopify.

## Failure Information

Digging into the package, I saw that webhooks are installed by WebhookInstaller job, which is queued by AuthenticateShop.
However, only ScripttagInstaller job appears in `jobs` table, WebhookInstaller job does not appear in `jobs` table.

Please help provide information about the failure if this is a bug.

### Steps to Reproduce
For some reason, when `AuthenticateShop.php` is executed,
https://github.com/Kyon147/laravel-shopify/blob/bdb7e74fe252334dbd6ea77ca51dab63fd3eb5d7/src/Actions/AuthenticateShop.php#L103-L106

ScripttagInstaller job from line 104 appears in `jobs` table and is subsequently dispatched.
WebhookInstaller job from line 105 does not appear in `jobs` table.

Out of curiousity, I swapped them

```
// Fire the post processing jobs
call_user_func($this->dispatchWebhooksAction, $result['shop_id'], false); // now, only this appears in `jobs`
call_user_func($this->dispatchScriptsAction, $result['shop_id'], false); // this does not appear in `jobs`
call_user_func($this->afterAuthorizeAction, $result['shop_id']);
```

I did try to upgrade to the latest version 19.0 but it gave other errors `Class "Osiset\BasicShopifyAPI\Store\Memory" not found` and I decided not to pursue it

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- Package Version: v18.2.0
- OS version: Ubuntu 22.04.2 LTS
- PHP version: 8.1.18
- Laravel version: 8.83.27
- Template Engine: Blade

### Failure Logs

No errors appear in laravel.log

Please include any relevant log snippets or files here.

**Comment by sp-artisan** [comment]
I think I know where is the actual problem. I faced the similar issue in one of my old app while updating the package.
As per I can assume @bilogic you are upgrading the package version in from the old version.
And we had an upgrade in the shopify-app.php which is in the config folder.

As we have updated the namesapces from Osiset to Gnikyt. We must also updated those namespaces in the shopify-app.config file.

You will need to update these three config values to the new namespaces from the old one.
![image](https://github.com/Kyon147/laravel-shopify/assets/92091678/313f37c6-d8e4-46f9-8887-9a862ebb65dc)

I think @Kyon147 it will solve these new issues.

**Comment by bilogic** [comment]
@sp-artisan 

There are 2 issues here, let's not discuss them together. I'm aware of how to solve the namespace problem already. The bigger issue is the jobs not being queued.

**Comment by sp-artisan** [comment]
> @sp-artisan
> 
> There are 2 issues here, let's not discuss them together. I'm aware of how to solve the namespace problem already. The bigger issue is the jobs not being queued.

I noticed that `Osiset\BasicShopifyAPI\Store\Memory` class thing from your question so I thought it would be good to post it here if somebody else finds it out it could work for them if they are upgrading.

**Comment by bilogic** [comment]
Yes, appreciate the help. Thank you.

**Comment by Kyon147** [comment]
@bilogic i've done some tests on a new local app and can't replicate the issue. Are you on our discord, as you could DM me some more detail on your app set up so I can try and replicate it more specifically this weekend when I have time.

**Comment by bilogic** [comment]
Thanks for getting back. Not sure what happened, but I kept trying to clear the config cache and re-installing in shopify. Eventually the issue went away. Thank you.

**Comment by Kyon147** [comment]
@bilogic glad you manage to fix it, sounds like something may have cached that was causing an issue.
