### ISSUE TITLE
APP scopes not updating

### ISSUE THREAD

**Issue by slashcart** [Kyon147/laravel-shopify#185]
We added  new scopes while ago but many stores still running with old scopes. we checked few stores and find out they are using too old scopes. and there is no update prompt to update scopes when we re open the app , we even tried removing auth token from our database but still shop is not merchant is not re authenticating. on the other hand on newly installed stores and for few old stores scopes are updated. But stores we check are not updating scopes.
What can be the  issue?
Note that scopes are set as per guide and working fine for many stores

**Comment by usmanpakistan** [comment]
@slashcart Please refer to solution #186
