### ISSUE TITLE
[API] Invalid API key or access token (unrecognized login or wrong password)

### ISSUE THREAD

**Issue by malikhammad12** [Kyon147/laravel-shopify#189]
When i hit my billing url, then error the following error comes....*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

Working on
    "kyon147/laravel-shopify": "^19.0",
![error](https://github.com/Kyon147/laravel-shopify/assets/140239230/798f2de0-075c-4734-aae0-4b9144765c5c)
![network](https://github.com/Kyon147/laravel-shopify/assets/140239230/9dc5087a-6e89-4c11-97f6-9a17406a16b5)

        "laravel/framework": "^10.10"

This is my code of billing url....
                               <a href="{{ URL::tokenRoute('billing',['plan' => 1, 'shop' => Auth::user()->name, 'host' =>  app('request')->input('host') ]) }}"><button>Upgrade</button></a>

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

Please describe the current behavior?

## Failure Information

Please help provide information about the failure if this is a bug.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
2. Step 2
3. ...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: vX.Y.Z
* Laravel Version: vX.Y.Z
* PHP Version: vX.Y.Z
* Template Engine: Blade or React
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Kyon147** [comment]
That error is telling you the potential issue, your API credentials are not correct or your api scopes are not right. 

Going to close this until you have more information as the screenshot is too vague.

**Comment by Asenwang** [comment]
When you use  "laravel/framework": "^10.10", you should remove as below In User Model
![image](https://github.com/Kyon147/laravel-shopify/assets/15796935/7ba67ea6-0bb9-422f-9354-012ca313e64c)
