### ISSUE TITLE
missing auth url 

### ISSUE THREAD

**Issue by saqlainkhadim** [Kyon147/laravel-shopify#193]
missing auth url shopify Laravel app error 
	"php": "^8.1",
        "kyon147/laravel-shopify": "^19.0",
        "laravel/framework": "^10.10",
        
![image](https://github.com/Kyon147/laravel-shopify/assets/94662735/a6ee2dd5-bfb4-4201-beeb-3a4f3ad37a55)

![image](https://github.com/Kyon147/laravel-shopify/assets/94662735/3d388f1c-113b-4959-b58e-c7bced072b95)

**Comment by Kyon147** [comment]
@saqlainkhadim please provide more details that just a screenshot. 

This is usually down to the package / shopify app not being configured correctly.

Closing until more info is provided.

**Comment by saqlainkhadim** [comment]
when I got to the Shopify app and load my test app it shows me this error.
here are my environment details
"php": "^8.1",
"kyon147/laravel-shopify": "^19.0",
"laravel/framework": "^10.10",

let me know i what what more details you want to know.

**Comment by codersaiful** [comment]
![image](https://github.com/Kyon147/laravel-shopify/assets/6463919/bc624aa2-9eba-4322-9d1b-291260d40c42)
Same Issue, How can I fix it.
No solution here founded.
