### ISSUE TITLE
App not loaded on navigation to next page

### ISSUE THREAD

**Issue by sandeshpaudyal** [Kyon147/laravel-shopify#196]
The app is loading when we open the app. But when we navigate to different routes, the app does not load and we also donot have any error log on laravel.log and also on console.

Route::get('/',[HomeController::class,'index'])->middleware(['verify.shopify'])->name('home');
This route is working

Route::get('/products',[ProductController::class,'index'])->middleware(['verify.shopify'])->name('products');
On this route, the app doesnot load. I have tried to log on controller too.

**ProductController**

class ProductController extends Controller
{
    public function index()
    {
        $shop = Auth::user();
        $shopDomain = Auth::user()->name;
        $query = $this->generateQuery('10');
       // var_dump(json_encode($query));
        $result = $shop->api()->graph($query);
        return view('product')->with('data', $result['body']);
    }
}

**View : product**
<h1>Product page</h1>

* Laravel Version: 8.0
* PHP Version: 8.1

**Comment by Kyon147** [comment]
You are not using the tokenRedirect helpers. Please read the wiki https://github.com/Kyon147/laravel-shopify/wiki/Authentication-Process
