### ISSUE TITLE
Host param is being unset on SPA

### ISSUE THREAD

**Issue by ncpope** [Kyon147/laravel-shopify#200]
## Expected Behavior

I am seeing the host param removed when using React and verify.shopify middleware on web.php routes. This is required to get app bridge 3.1 working correctly.

## Current Behavior

When I do a dump of the request I see all of the original request parameters. However, after doing a dump after a new shop is authenticate the host param is being unset.

## Failure Information

<img width="635" alt="Screenshot 2023-08-19 at 12 55 35" src="https://github.com/Kyon147/laravel-shopify/assets/1903724/1801efcb-5763-4138-9d1e-e2538aab1658">

<img width="732" alt="Screenshot 2023-08-19 at 12 57 50" src="https://github.com/Kyon147/laravel-shopify/assets/1903724/21c56d03-b804-44fc-ae2d-13b254c02ca7">

<img width="595" alt="Screenshot 2023-08-19 at 12 58 14" src="https://github.com/Kyon147/laravel-shopify/assets/1903724/4e555a8e-e3d6-436f-996b-d1e409656769">

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use middleware ('verify.shopify');

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v19.0.0
* Laravel Version: v10.19.0
* PHP Version: v8.2.4
* Template Engine: React
* App Bridge: 3.1.1
* Using a toolset : Remote on digital ocean / forge, local on valet - same results

**Comment by ncpope** [comment]
This was tested on a production app and it has resolved the issue. Previously, new merchants were unable to install the app.

**Comment by Kyon147** [comment]
@ncpope I can see you closed the pull request - what was the reason? 

I use SPA on my apps, and have no run into any issues - so would be good to know if there is still a bug somewhere.

**Comment by ncpope** [comment]
@Kyon147 I made further changes to the branch on my repo not knowing that it would automatically update the pull request here.

The additional fixes were going to be just specific to my apps needs and were not meant to update the pull request. I will create a new pull request after I undo the changes.

Can I ask what your setting value is for `SHOPIFY_FRONTEND_ENGINE`?

**Comment by Kyon147** [comment]
I use `REACT` but use Vue as the FE as I think we never actually implemented `VUE` as a value but it is meant to do the same thing. I'll need to check to see if it was every updated.
