### ISSUE TITLE
Duplicated charge_id error while updating the old capped amount

### ISSUE THREAD

**Issue by devRonak** [Kyon147/laravel-shopify#202]
@Kyon147 I have recently changed my capped amount for the app, but the user who installed the app before changing the capped amount is still getting the old capped amount, so I am using this [API](https://shopify.dev/docs/api/admin-rest/2023-07/resources/recurringapplicationcharge#put-recurring-application-charges-recurring-application-charge-id-customize?recurring-application-charge[capped-amount]=200) to update it. I get "update_capped_amount_url" in the response of this API. When we go to this URL, permission is sought from the user to approve the new capped amount. When the user clicks on the approve button, the "laravel-shopify" package tries to insert a new entry in the "charges" table. But the old "charge_id" is already filed in the table of charges, it is UNIQUE, due to which the error of Duplicate entry is coming. Do you have any suggestions for this thing?

![2](https://github.com/Kyon147/laravel-shopify/assets/42402696/04dfc9c6-0f27-4994-925c-a8dbe282fefe)
![1](https://github.com/Kyon147/laravel-shopify/assets/42402696/f7b24dfc-25e8-4791-82a4-a088ef8155d6)

**Comment by Kyon147** [comment]
Hi @devRonak 

Late reply but charges do have to be unique, Shopify requires you to ask the customer to re-approve any subscription with changes. So this would need to be a new charge and removing the older one.
