### ISSUE TITLE
I don't have any  login route.

### ISSUE THREAD

**Issue by bmtamim** [Kyon147/laravel-shopify#204]
![image](https://github.com/Kyon147/laravel-shopify/assets/52544492/1eebbec3-6829-4465-bb94-ae8f68d5d4bd)

When I enter my website root URL in browser its redirect me into this "/authenticate" page and show me the error  "No authenticated user or shop domain"

BTW,  I have hosted it into cloudways and got same issue. 

And, when first time I installed the app in any store its fine , but when I uninstall the app from store and install it then got 404 error.

**Comment by rvibit** [comment]
Your appuninstalled webhook is not firing, that's why when app is uninstalled the deleted_at column is not filled with current timestamp and that's the reason you are unable to install the app on same store again

**Comment by bmtamim** [comment]
@rvibit  Thanks for the reply sir, how can I fire the uninstall than? And Why In my application there doesn't have login route, as your documents tell us? login route will be provided.
Thanks Again

**Comment by rvibit** [comment]
> @rvibit Thanks for the reply sir, how can I fire the uninstall than? And Why In my application there doesn't have login route, as your documents tell us? login route will be provided. Thanks Again

check uninstall JOB section in this doc and Authentication Process section as well https://github.com/Kyon147/laravel-shopify/wiki

**Comment by bmtamim** [comment]
@rvibit Thanks again sir, What about the login route?
![image](https://github.com/Kyon147/laravel-shopify/assets/52544492/74f9c546-b9b9-4563-9c8f-53dfccadaa77)

**Comment by rvibit** [comment]
> @rvibit Thanks again sir, What about the login route? ![image](https://user-images.githubusercontent.com/52544492/263904513-74f9c546-b9b9-4563-9c8f-53dfccadaa77.png)

Why you need a Login route can you explain the use case ? The Authentication Process doc explains how the authentication works in this package.

**Comment by bmtamim** [comment]
If someone try to hit my application in the browser they get the error. But I saw your previous version had a login route when someone enters the site URL outside Shopify they redirect to login and ask for the Shopify store URL for the login process.

**Comment by rvibit** [comment]
> If someone try to hit my application in the browser they get the error. But I saw your previous version had a login route when someone enters the site URL outside Shopify they redirect to login and ask for the Shopify store URL for the login process.

https://github.com/gnikyt/laravel-shopify/issues/1208 check this

**Comment by Kyon147** [comment]
@bmtamim `/login` as a route was taken out a while back even on the original package. That is why you no longer see it, you can bring it back yourself fairly easily but it might be against the new TOS for Shopify as I vaguely remember that was why it was removed way back.
