### ISSUE TITLE
the installation date is not taking the timezone configured in the laravel app

### ISSUE THREAD

**Issue by dandyleon19** [Kyon147/laravel-shopify#205]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

When installing the app, when the charge is created, the "billing_on" and "activated_on" fields should take the timezone configured in the Laravel app.

## Current Behavior

At the time of installing the app, when the charge is created, the "billing_on" and "activated_on" fields are being created with the UTC timezone

### Context

* Package Version: v17.5.0
* Laravel Version: v8.83.27
* PHP Version: v7.4

### Failure Logs

In this example, the app was installed on 2023-08-27, but since it is taking the UTC timezone, it is creating the record with 2023-08-28 and consequently the end date of the trial_end_on is increased by one more day

![image](https://github.com/Kyon147/laravel-shopify/assets/48505581/3706bb68-3080-450a-91c2-9b0e79542456)

**Comment by Kyon147** [comment]
@dandyleon19 UTC is quite standard for most server side date fields and is usually recommend. As most apps, SaaS products just format the date in the client based on the UTC value.
