### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by yamakrane** [Kyon147/laravel-shopify#206]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

- Install Laravel 10
- Composer require Kyon147 / laravel-shopify
- Installing laravel-shopify
- Linking Valet with secured domain
- Installing custom App in Shopify Partners
- Adding test1, test2, test3 routes and views and navbar

## Current Behavior

When i try to navigate between routes to view pages, it doesnt work

## Failure Information

The first time I enter the app to view the welcome page in the embeded app, it works just fine, but as soon as I click on a different link it stops working as if it is missing authentication.

1 st time i get this url:
<img width="1440" alt="image" src="https://github.com/Kyon147/laravel-shopify/assets/38190169/398ebb43-16af-4040-9290-d50f9b04e69c">

after hitting a link i get this:
<img width="1199" alt="image" src="https://github.com/Kyon147/laravel-shopify/assets/38190169/cb14fa9b-3684-42c8-9e6a-86417b94812f">

<img width="1430" alt="image" src="https://github.com/Kyon147/laravel-shopify/assets/38190169/d2455099-a22d-49eb-8c19-9a30780167c7">

The URL of getting the token changes, the response of the second one is just a placeholder a believe.

**Comment by yamakrane** [comment]
href="{{ URL::tokenRoute('customers') }}"

**Comment by Kyon147** [comment]
Just to add, this is in the wiki - if you get stuck please read the wiki.
