### ISSUE TITLE
Infinite Loop on app page with fresh installation (19.1)

### ISSUE THREAD

**Issue by faridmovsumov** [Kyon147/laravel-shopify#215]
I have a fresh installation (19.1), and I am facing an infinite loop between the token and home endpoints.

https://kuzey.eu-1.sharedwithexpose.com/authenticate/token?shop=azerify.myshopify.com&target=%2F%3Fembedded%3D1%26host%3DYWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYXplcmlmeQ%26token%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczpcL1wvYXplcmlmeS5teXNob3BpZnkuY29tXC9hZG1pbiIsImRlc3QiOiJodHRwczpcL1wvYXplcmlmeS5teXNob3BpZnkuY29tIiwiYXVkIjoiMDc0ZTZlMTdjNzAwZTliMDU3OGU3NmM0YjI4NGNmNzkiLCJzdWIiOiI3MzA4MDYwMjY4MiIsImV4cCI6MTY5NjE4NjA4MywibmJmIjoxNjk2MTg2MDIzLCJpYXQiOjE2OTYxODYwMjMsImp0aSI6IjFmYjY0NTE4LTUzNTctNGQ5Ny1hY2QxLWE0YjVmZGE3ZTkyMiIsInNpZCI6IjdhNGI3NmQyMGFkYzg1N2U1NWM3NWYzNzk0NGM5OWE5OTc2MjUxNDQ4M2JjMTgyZTMxZTBiNGYxZTcxYzZlMTcifQ.cjJU57IM47DuXrbTxGe6P534sAnsoXwP0lAYGDO9f-Y&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYXplcmlmeQ

https://kuzey.eu-1.sharedwithexpose.com/?embedded=1&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYXplcmlmeQ&shop=azerify.myshopify.com&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczpcL1wvYXplcmlmeS5teXNob3BpZnkuY29tXC9hZG1pbiIsImRlc3QiOiJodHRwczpcL1wvYXplcmlmeS5teXNob3BpZnkuY29tIiwiYXVkIjoiMDc0ZTZlMTdjNzAwZTliMDU3OGU3NmM0YjI4NGNmNzkiLCJzdWIiOiI3MzA4MDYwMjY4MiIsImV4cCI6MTY5NjE4NjA4MywibmJmIjoxNjk2MTg2MDIzLCJpYXQiOjE2OTYxODYwMjMsImp0aSI6IjFmYjY0NTE4LTUzNTctNGQ5Ny1hY2QxLWE0YjVmZGE3ZTkyMiIsInNpZCI6IjdhNGI3NmQyMGFkYzg1N2U1NWM3NWYzNzk0NGM5OWE5OTc2MjUxNDQ4M2JjMTgyZTMxZTBiNGYxZTcxYzZlMTcifQ.cjJU57IM47DuXrbTxGe6P534sAnsoXwP0lAYGDO9f-Y

I have a fresh Laravel installation, and I have a fresh installation of the library.

<img width="659" alt="image" src="https://github.com/Kyon147/laravel-shopify/assets/1541412/a6d3d836-6012-434e-9c34-baa20d22939b">

You can see below the screenshot of what it looks like.

![image](https://github.com/Kyon147/laravel-shopify/assets/1541412/89d69731-0aab-45f4-8fa7-e40baa11a502)

Some var_dumps in the case can be helpful. 

<img width="1180" alt="image" src="https://github.com/Kyon147/laravel-shopify/assets/1541412/7c29e5ee-dbdf-416a-a348-fcd8841d50da">

Additionally, I am running Laravel on Mac with Laravel Sail and using expose.dev service for https.

Also, I added some debugging to token.blade.php, and the redirect URL has a host parameter twice. It feels like something is wrong there. 

<img width="1478" alt="image" src="https://github.com/Kyon147/laravel-shopify/assets/1541412/a9d66c92-4fe2-4b02-9da9-3fad789b0979">

https://kuzey.eu-1.sharedwithexpose.com/authenticate/token?shop=azerify.myshopify.com&target=/?embedded=1&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYXplcmlmeQ&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczpcL1wvYXplcmlmeS5teXNob3BpZnkuY29tXC9hZG1pbiIsImRlc3QiOiJodHRwczpcL1wvYXplcmlmeS5teXNob3BpZnkuY29tIiwiYXVkIjoiMDc0ZTZlMTdjNzAwZTliMDU3OGU3NmM0YjI4NGNmNzkiLCJzdWIiOiI3MzA4MDYwMjY4MiIsImV4cCI6MTY5NjE4NTQ1MSwibmJmIjoxNjk2MTg1MzkxLCJpYXQiOjE2OTYxODUzOTEsImp0aSI6ImJhODEyNjcyLWIzZGUtNGFjNy1iYzg4LTY1N2E0YmFlZWJkMyIsInNpZCI6IjdhNGI3NmQyMGFkYzg1N2U1NWM3NWYzNzk0NGM5OWE5OTc2MjUxNDQ4M2JjMTgyZTMxZTBiNGYxZTcxYzZlMTcifQ.VkfMFSnHMiBrVXE7IEXvDOuIlBKUOYGjvLTypPtAox4&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYXplcmlmeQ

**Comment by Kyon147** [comment]
@faridmovsumov do you get this all the time? ]

I've seen this issue before with those using blade templates, that sometimes, the redirect URL is set at /token so a infinite loop happens.

**Comment by faridmovsumov** [comment]
@Kyon147 Yes, at the moment, I get it all the time, and it is kind of blocking me from starting. I tried to debug to understand the reason but no success so far.

**Comment by faridmovsumov** [comment]
I am doing some debugging, so I will add my findings here.

Exception is being thrown inside VerifyShopify Middleware

<img width="691" alt="image" src="https://github.com/Kyon147/laravel-shopify/assets/1541412/5264719c-5dfa-4c99-97d3-d65cfce3061b">

**Comment by faridmovsumov** [comment]
<img width="1068" alt="image" src="https://github.com/Kyon147/laravel-shopify/assets/1541412/c32e5031-ab29-480f-a840-e0fe99c06c9b">
Seems like token is expired. Expiration date set to now.
<img width="1312" alt="image" src="https://github.com/Kyon147/laravel-shopify/assets/1541412/4e77c6bf-626b-473f-b0bf-a8d46fd4d944">

**Comment by Kyon147** [comment]
Token's only live for 1 minute, but the auth/token route should ask again for a new token each time to get whatever one is valid.

**Comment by faridmovsumov** [comment]
Ok, I finally found the reason for this weird bug. It was occurring because the time settings of my machine somehow weren't matching with the server's time settings. I simply set it on Mac to be set automatically and the problem is fixed.

![image](https://github.com/Kyon147/laravel-shopify/assets/1541412/192f5e0c-ae87-4f29-bfcd-f22897948301)

Thanks for support @Kyon147

**Comment by Kyon147** [comment]
@faridmovsumov I'm glad you found the issue. I've seen the time sync issue pop up a couple times actually thinking back.

I might add a common issues page to the wiki and add this on to it.
