### ISSUE TITLE
App install error : Oauth error invalid_request: The redirect_uri is not whitelisted 

### ISSUE THREAD

**Issue by searchfy** [Kyon147/laravel-shopify#219]
I'm getting a "Oauth error invalid_request: The redirect_uri is not whitelisted" error on app installs, eventhough redirect url is set on App Settings (Allowed redirection URLs)

App is running from phpsandbox.io with Laravel 10 and the latest shopify package

**Comment by Kyon147** [comment]
Can you send a screenshot of your redirect urls. This error is pretty specific so usually the error is what it says.

**Comment by Kyon147** [comment]
Closing as no more information but reopen when you have more.

**Comment by ksidibe** [comment]
I'm having the same issue.
Here's a screenshot:
<img width="1345" alt="Screenshot 2024-02-18 at 8 02 51 AM" src="https://github.com/Kyon147/laravel-shopify/assets/3746660/a4f68aba-80d2-4777-8830-fada7c78b262">

My **local** dev app is accessible via  https://shopapp.com.
I tunnel to this local app via Ngrok. The url configs in the Shopify app are set as shown in the screenshot below

<img width="1008" alt="Screenshot 2024-02-18 at 8 06 57 AM" src="https://github.com/Kyon147/laravel-shopify/assets/3746660/d32403d0-e72f-41f2-94f8-de482dce48fa">

**Comment by achaldineshgahlot** [comment]
I got the same issue
