### ISSUE TITLE
Undefined index: shop_auth_provider

### ISSUE THREAD

**Issue by DevStackRahul** [Kyon147/laravel-shopify#220]
I have upgrade the package from osiset to kyon147 it gives the error "Undefined index: shop_auth_provider".

## Current Behavior

[Undefined index: shop_auth_provider](https://prnt.sc/34CEgcXNSwO1)

## Failure Information

Please help provide information about the failure if this is a bug.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
composer remove osiset/laravel-shopify
2. Step 2
composer require kyon147/laravel-shopify

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: kyon147 17.1
* Laravel Version: 7.0
* PHP Version: 7.2
* Template Engine: Blade 
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Kyon147** [comment]
Closing this as we've spoken in the Discord that you are missing some migrations and need to manually update.
