### ISSUE TITLE
Not getting redirected to charge step?

### ISSUE THREAD

**Issue by ashdevelops** [Kyon147/laravel-shopify#226]
I have followed everything listed here to enable billing: https://github.com/Kyon147/laravel-shopify/wiki/Creating-a-Billable-App

## Expected Behavior

I'm redirected to a charge pre-authorization screen.

## Current Behavior

App is installed without charge authorization

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install v19.0 of package with latest Laravel
2. Install from fresh shopify app
3. Notice how it doesn't show charge authorization screen

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: 19.0
* Laravel Version: Latest / 10
* PHP Version: 8.2
* Template Engine: Blade
* Using ngrok local tunnel

**Comment by Kyon147** [comment]
@ashdevelops are you using blade template or SPA? Do your routes have the `billable` middleware on them?

**Comment by ashdevelops** [comment]
Hi @Kyon147 I am using blade templates. Also I am using the default installation routes which states it has billable middleware by default on these ones.

**Comment by Kyon147** [comment]
@ashdevelops you still need to add `billable` middleware to all the routes including the home route. Otherwise you won't be redirected to the billing screen

**Comment by ashdevelops** [comment]
Thanks I've added billable, but now auth()->user() is null when trying to fetch the plan. Is there a reason for this?

**Comment by Kyon147** [comment]
Have you made sure you have both middleware on the route i.e `['billable','verify.shopify']`

**Comment by Kyon147** [comment]
Going to close this as I can not replicate and it sounds like you might be missing both middleware. Re-open if still an issue.
