### ISSUE TITLE
Trying to create private app returns 403 status

### ISSUE THREAD

**Issue by jabarrioss** [Kyon147/laravel-shopify#23]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

I want to create a test charge in my development private app

## Current Behavior

I created a private as I've always done but when I try to create a test charge, the ApiHelper returns status 403 when creating the new charge

## Failure Information

When the ApiHelper file does a request to the endpoint for create charges it returns 403

### Steps to Reproduce

1. Create a new private app
2. Activate the billing withing your env file
3. Try to install the store fresh, this will not work if the store already exist in you database

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: "osiset/laravel-shopify": "^17.3"
* Laravel Version: v 8.83.25
* PHP Version: v7.4.19
* Template Engine: Blade
* Using a toolset (Docker, Laradock, Vagrant, etc.): Laragon

### Failure Logs

[previous exception] [object] (GuzzleHttp\\Exception\\ClientException(code: 403): Client error: `POST https://shopbasemiddleman.myshopify.com/admin/recurring_application_charges.json` resulted in a `403 Forbidden` response at C:\\laragon\\www\\wsconfirm\\vendor\\guzzlehttp\\guzzle\\src\\Exception\\RequestException.php:113)

**Comment by Kyon147** [comment]
Hi @jabarrioss 

By the nature of private/customer apps, they are not allowed to use the billing api. Which you can read here: https://shopify.dev/apps/distribution#capabilities-and-requirements

You need to set up a public app if you wish to use the built in billing.
