### ISSUE TITLE
Class "Osiset\BasicShopifyAPI\Store\Memory" not found

### ISSUE THREAD

**Issue by kkang386** [Kyon147/laravel-shopify#231]
## Expected Behavior

Should be able to install embedded app to a testing store.

## Current Behavior

It hangs with errors in the log:

## Failure Information

Installed the newest lib version 19.1.0  with php 8.1.25, and installed `gnikyt/basic-shopify-api `ver 11.0. Then the log file shows this when installing the embeded app to a new store:
` /var/www/vendor/kyon147/laravel-shopify/src/Http/Middleware/VerifyShopify.php(77): Osiset\ShopifyApp\Services\ApiHelper->make()
#1 [internal function]: Osiset\ShopifyApp\Http\Middleware\VerifyShopify->__construct(Object(Illuminate\Auth\AuthManager), Object(Osiset\ShopifyApp\Services\ApiHelper), Object(Osiset\ShopifyApp\Storage\Queries\Shop))
`
Tried with installing `osiset/basic-shopify-api `ver 11.0, got the same error, because the autoloader is trying to load `gnikyt/basic-shopify-api `, and the verifyShopify is trying to load the other one.

### Steps to Reproduce

See the previous step

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v19.1.0
* Laravel Version: v9.51
* PHP Version: v8.1.25
* Using a toolset : Docker
* gnikyt/basic-shopify-api: v11.0.0
* osiset/basic-shopify-api: v11.0.0

**Comment by Kyon147** [comment]
@kkang386  you should not need to install the Shopify api package yourself, it is a dep within the package itself so gets added.

You could be getting this issue because of that. Try removing it from your composer file and running `composer update` again.

**Comment by Kyon147** [comment]
Assuming my comment worked, so going to close this but reopen if still and issue

**Comment by haseebsoftwreng** [comment]
cause same issue for me when i update from 18 to 19 version
"require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "kyon147/laravel-shopify": "^19.1",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/telescope": "^4.17",
        "laravel/tinker": "^2.8"
    },
