### ISSUE TITLE
Trying the Event Listener System, Facing Typecasting Issue

### ISSUE THREAD

**Issue by rgopalakeans** [Kyon147/laravel-shopify#241]
https://github.com/Kyon147/laravel-shopify/wiki/Event-Listener-System#appinstalledeventclass

With help of above, trying to create a "AppInstalledEventListener" to sending a mail to merchart & admin after App getting installed.

## /html/config/shopify-app.php
`    'listen' => [
        \Osiset\ShopifyApp\Messaging\Events\AppInstalledEvent::class => [
            \App\Listeners\SendAppInstalledEmailListener::class,
        ],
    ]
`
## /html/app/Listeners/SendAppInstalledEmailListener.php
`<?php
namespace App\Listeners;

use Illuminate\Bus\Queueable;
use Illuminate\Support\Facades\Mail;
use Illuminate\Contracts\Queue\ShouldQueue;
use Osiset\ShopifyApp\Messaging\Events\AppInstalledEvent;
use Illuminate\Support\Facades\Log;

class SendAppInstalledEmailListener implements ShouldQueue
{
    use Queueable;
    /**
     * Create the event listener.
     *
     * @return void
     */
    protected Shop $shop;

    public function __construct()
    {
        $this->onQueue('default');
    }

    /**
     * Handle the event.
     *
     * @param  object  $event
     * @return void
     */
    public function handle(AppInstalledEvent $event)
    {
        $user_id    = $event->shopId;
        $user_email = \App\Models\User::where('id', $user_id)->value('email');

        echo '<pre>';
            print_r( 'User ID: '.$user_id );
            print_r( 'User Email: '.$user_email );
        echo '</pre>';

        Log::debug('App Installed Event Listener...');
    }
}`
## Issue & log
**Object of class Osiset\ShopifyApp\Objects\Values\ShopId could not be converted to string**

## When print with die
![screen1](https://github.com/Kyon147/laravel-shopify/assets/135309255/7909138d-2863-4d7e-a6d2-ec3231e33650)

## Request
How to use the $shop_id to get shop user email?
Please help us to use this "Event & Listener System".

## Note
We tried many ways to to convert as a string ,int, json but no success.

* Package Version: Current Development Version
* Laravel Version: v8.83.27
* PHP Version: v8.1.25
* Using a toolset (Docker, Laradock, Vagrant, etc.):None

Thanks,
Gopal R

**Comment by shawon922** [comment]
@rgopalakeans 
Try like this
`$user_id = $event->shopId->toNative();`

**Comment by rgopalakeans** [comment]
Hi @shawon922, 

Thanks for your response. Will try same and let you know, if any issues.

Thanks,
Gopal R

**Comment by thanhnv37** [comment]
Hi all,

How do you get the shop email on the event AppInstalledEvent?
The email stored in the user table is not the correct email.

I tried using the API get shop
https://shopify.dev/docs/api/admin-rest/2024-04/resources/shop#get-shop

But the method Auth::user(); return null on this event.
So when I call the method Auth::user()->api()->rest();
it returned error.

Thank you for your help.

Thanks,
Thanh Nguyen

**Comment by thanhnv37** [comment]
@Kyon147 @shawon922 @rgopalakeans could you please help? thank you.

**Comment by thanhnv37** [comment]
Below is my code:

```
public function handle(AppInstalledEvent $event)
  {
    $shop = Auth::user();
    $data = $shop->api()->rest('GET', '/admin/shop.json')['body']['shop'];
  
    Mail::to($data['email'])->send(new AppInstalled($data));
  }
```
