### ISSUE TITLE
Access Scope

### ISSUE THREAD

**Issue by Ansari-techs** [Kyon147/laravel-shopify#249]
"errors": "[API] This action requires merchant approval for read_products scope."
    
    i create Shopify App Using Laravel Osiset Package and define api-scopes in config/shopify-app.php file now i install app on installation scopes not showing in URL and using store access token hit product rest Api so facing this issue => "errors": "[API] This action requires merchant approval for read_products scope."

**Comment by Kyon147** [comment]
@Ansari-techs when you change or add scopes you need to push them back to /authenticate or if you are on v19.2 you can use the `verify.scopes` middleware
