### ISSUE TITLE
Getting Issue when using GET and POST methods in some cases

### ISSUE THREAD

**Issue by rgopalakeans** [Kyon147/laravel-shopify#256]
First up all, Thanks for the great package.

We have an app, it supports to add unlimited options for the user. We tried below,
## In routes/web.php
Route::get('/manage/addnewrule', []);
Route::get('/manage/updaterule', []);

## In manage.blade.php & manage-edit.blade.php
`<form id="frmRuleID" method="get" action="{{ route('shopify.manage.addnewrule') }}">`
`<form id="frmRuleID" method="get" action="{{ route('shopify.manage.updaterule') }}">`

## Trying to add more options
![options](https://github.com/Kyon147/laravel-shopify/assets/135309255/0de46abd-dff1-432c-a0cb-3cdcc8132d54)

## But we got error below,
![error1](https://github.com/Kyon147/laravel-shopify/assets/135309255/de2ed3e4-403c-4e3b-977c-bf1b8277dbb0)

----------------------------------------------------------------------------------------------------------------------------------------------------------------
**Tried Way II:**

## In routes/web.php ( Instead of get, post method used )
Route::post('/manage/addnewrule', []);
Route::post('/manage/updaterule', []);

## In manage.blade.php & manage-edit.blade.php ( method="post" )
`<form id="frmRuleID" method="post" action="{{ route('shopify.manage.addnewrule') }}">`
`<form id="frmRuleID" method="post" action="{{ route('shopify.manage.updaterule') }}">`

## But we got error below,
![error2](https://github.com/Kyon147/laravel-shopify/assets/135309255/c9bad38c-deb0-47ec-ac52-fa427a6efa32)

**_Note: The above error, we got not all the time. If we trying with 25% options it adding & updating, But when try complete options update, get the above error. Please guid us to solve this issue?_**

Thanks,
Gopal R

**Comment by rgopalakeans** [comment]
@Kyon147 Did you checked the above issue?

**Comment by Kyon147** [comment]
Closing stale issue
