### ISSUE TITLE
How to downgrade user to Freemium?

### ISSUE THREAD

**Issue by faridmovsumov** [Kyon147/laravel-shopify#258]
I want to give users the ability to downgrade to Free Plan. This means they should be able to cancel their current plan.  How can I achieve this?

I tried to create a Plan on the database with price 0, but I got an error while trying this. What is the right way of doing this?

**Comment by cyberkishor** [comment]
Hi @faridmovsumov, 

Shopify does not allow us to charge a price with a 0 value so, so what can we do is set the `price` 0 and `capped_amount` <any value> like 4.00

![Screenshot 2024-01-10 at 11 52 39](https://github.com/Kyon147/laravel-shopify/assets/2122140/f6eaf7c8-a96a-4863-8577-95922c495c70)

Let me know if you need any help.

**Comment by cyberkishor** [comment]
@Kyon147 Let's include this information in billing wiki page.

**Comment by faridmovsumov** [comment]
> cyberkishor

Thanks for the suggestion; I ended up implementing some custom solutions. Also, how do you allow users to continue using their current plan until the end of the period after they downgrade to the free plan? And what does user see on the screen when they are switching to Free plan, does it show something regarding capped amount?

**Comment by cyberkishor** [comment]
@faridmovsumov To handle the subscription end we have a captures table with an `expires_on` value, you can limit user based on that. And user have to approve the capped amount but it's not charged I think. 

![Screenshot 2024-01-10 at 12 14 32](https://github.com/Kyon147/laravel-shopify/assets/2122140/9554e90a-cc37-4628-ac47-72ab231dd5ef)

**Comment by faridmovsumov** [comment]
Thanks for sharing 🙏
