### ISSUE TITLE
Theme App Extension Support with kyon147

### ISSUE THREAD

**Issue by nandpalmohit** [Kyon147/laravel-shopify#259]
## Shopify Theme Extension

As of now Shopify with version **2023-04** or later is not **supported** (deprecated) as Shopify **restricts** the theme access to do the changes. Instead, Shopify provides to use of **Theme App Extension** or **Theme embed** codes to add liquid sections or add blocks in the Shopify theme.

My question is any possibility of doing this operation with this package and if yes, then how we can perform this operation with the kyon147 package?

**Comment by matthewhaworth** [comment]
Hello @nandpalmohit,

The way I went about this was to basically add the following to your `package.json`

```
        "shopify": "shopify",
        "shopify-build": "shopify app build",
        "shopify-dev": "shopify app dev",
```

under 'scripts'. Then, you can run `npm run shopify app generate extension` which will create an extensions folder in your laravel project root. From there, you can just carry on as per any Shopify tutorial.

**Comment by Kyon147** [comment]
As @matthewhaworth mentions you can use the Shopify cli. The theme extension is agnostic to the package - you could host it anywhere but inside the project makes the more sense.
