### ISSUE TITLE
Is there any setting for disabling  /authenticate/token call on each request? and instead, enable working like the older version.

### ISSUE THREAD

**Issue by HardikVansia** [Kyon147/laravel-shopify#26]
![image](https://user-images.githubusercontent.com/79184458/209127630-170e5db8-ed97-4cb5-aed3-d9d012f71b54.png)

**Comment by Kyon147** [comment]
The wiki contains everything you should need. 

You need to use the SPA support 

https://github.com/Kyon147/laravel-shopify/wiki/Installation#spa-support

This does mean that JWT tokens are no longer fetch before each request, so you will need to implement it yourself.
