### ISSUE TITLE
GraphQL API error messages handled incorrectly 

### ISSUE THREAD

**Issue by bastos71** [Kyon147/laravel-shopify#263]
## Expected Behavior

Printing the error message when receiving an error from API request.

## Current Behavior

Only "1" is returned, as you can see in the capture

![image](https://github.com/Kyon147/laravel-shopify/assets/3809299/3c4e9673-60ea-4731-889b-e986d581c12c)

Key `body` should be used in priority , here is what I get by doing `dd($response)` : 

![image](https://github.com/Kyon147/laravel-shopify/assets/3809299/736a7039-0526-4c84-8b92-41e9fd248cef)

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v19.2.0
* Laravel Version: v10.41.0
* PHP Version: 8.2.14
* Template Engine: Blade
* Using a toolset (Docker, Laradock, Vagrant, etc.): Docker

**Comment by Kyon147** [comment]
Hey @bastos71 

Can you explain a bit more on what the issue is, as your screenshot shows the response has `error` as `true` `and the body contains the error.

**Comment by bastos71** [comment]
Hi @Kyon147  !

I figured out the error was triggered because I forgot to disable `hashed` cast in `User` entity
I assume you can reproduce the issue by doing the same error ^^'

**Comment by Kyon147** [comment]
Ah right yeah, it makes the api passwords for each store unusable - glad you found the issue
