### ISSUE TITLE
install app button gets disabled using this package

### ISSUE THREAD

**Issue by jawadgit** [Kyon147/laravel-shopify#267]
## Expected Behavior

app install button should be enabled on newly created store

## Current Behavior

I am currently encountering an issue wherein the application can only be installed on Shopify stores 
that were created prior to the initiation of the app installation process in the Shopify admin panel.

Specifically, when attempting to install the app on a newly created store, the installation button becomes disabled, 
preventing the successful integration of the application with the store. I am seeking guidance on how to address and resolve this matter.

## Failure Information

Please remove the bug from the package so that any app using this package should be able to install on shopify store.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create one development store on shopify admin pane;
2. install app using this package to store
3. app gets install successfully
4. now create one new development store on same shopify admin panel
5. now try to install this app in newly created store.
6. the install app button gets disabled now and app will not be installed

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* nodejs Version: v20.10.0 
* Laravel Version: Laravel Framework 10.39.0
* PHP Version: "^8.1"
* Template Engine: React
* Using a toolset (Docker, Laradock, Vagrant, etc.): Docker

### Failure Logs

Please include any relevant log snippets or files here.
![stsstoreten-·-Authorize-stsappten-·-Shopify](https://github.com/Kyon147/laravel-shopify/assets/10416950/2e6738fe-abff-4cf4-8005-816e1751bb1b)

**Comment by Kyon147** [comment]
This is a Shopify screen, as we've talked about in the Discord so you'll have to speak with them on the issue.

If someone has any ideas though, they can add to your PR so I'll leave it open for a while

**Comment by Kyon147** [comment]
This was solved by running `php artisan config:clear  && php artisan cache:clear` based on the Discord chat.
