### ISSUE TITLE
Kyon Shopify Laravel "cURL error 28: Operation timed out after 10043 milliseconds with 0 bytes received (see https:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html) for https:\/\/*******.com\/admin\/api\/2024-01\/products.json"

### ISSUE THREAD

**Issue by slashcartshop** [Kyon147/laravel-shopify#273]
"cURL error 28: Operation timed out after 10043 milliseconds with 0 bytes received (see https:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html) for https:\/\/*******.com\/admin\/api\/2024-01\/products.json"
Kyon Shopify Laravel

**Comment by Kyon147** [comment]
Please format your issue correctly and supply more information about your issue. 

Will re-open once this is done.

**Comment by slashcartshop** [comment]
@Kyon147 
Thanks for response

Actually it was not library issue. It was because http request was taking time and the http request time out was short in laravel so i increased time out so its fixed.

Thanks

**Comment by koraysari** [comment]
@slashcartshop I'm facing the same issue. Can you explain how you solved it?

**Comment by mdzahid-pro** [comment]
I'm also getting the same issue while I'm trying to get  orders data from shopify graphql admin API
