### ISSUE TITLE
Urgent : Is it possible to pay in euros?

### ISSUE THREAD

**Issue by secureweb16** [Kyon147/laravel-shopify#276]
Hello @Kyon147 @gnikyt  @michaellehmkuhl @ericnkatz @joelvh @onurkose @Jamesking56 

Could please let me know is possible to pass the EUR currency, I tried to find the details on Google but I'm still not found anything. There is some API that this possible to pass the currency parameter but I'm using the below method for recurring payment. 

Attachment: https://prnt.sc/HQukqMDUtpBK

`<a href="{{ route('billing', ['plan' => 1, 'shop' => Auth::user()->name,'host' =>  app('request')->input('host') ]) }}" class="priceplanbutton standard_plans btn btn-dark" plan_id="">Buy </a>	`

**Comment by Jamesking56** [comment]
I don't think this package decides currency, I think that is configured via Shopify or your Laravel app

**Comment by Kyon147** [comment]
Shopify subscription is always in US as that is what they trade in.

**Comment by secureweb16** [comment]
@Kyon147 @Jamesking56 
 
Ok, Thank you
