### ISSUE TITLE
Class "Osiset\BasicShopifyAPI\Store\Memory" not found

### ISSUE THREAD

**Issue by casa-apps** [Kyon147/laravel-shopify#277]
I had install the osiset/laravel-shopify package and I was getting some issues there. now I have uninstall the osiset/laravel-shopify package and and then install the Kyon147/laravel-shopify.

I'm getting this error Class "Osiset\BasicShopifyAPI\Store\Memory" not found.

**Comment by Kyon147** [comment]
Please follow the update guide https://github.com/Kyon147/laravel-shopify/wiki/Upgrading

**Comment by casa-apps** [comment]
Thanks @Kyon147 

The issue was resolved by deleting old "shopify-app.php" file from config directory and then by running "php artisan vendor:publish --tag=shopify-config" command
