### ISSUE TITLE
Fix PHP 8.1 deprecated messages

### ISSUE THREAD

**Issue by Lotuashvili** [Kyon147/laravel-shopify#28]
Please update `osiset/basic-shopify-api` package to a v11.0.0 version, which fixes PHP 8.1 deprecation warnings, and also renames namespace from `Osiset` to `Gnikyt`. [Compare v11.0.0 to v10.0.6](https://github.com/gnikyt/Basic-Shopify-API/compare/v10.0.6...v11.0.0)

I am getting these errors now:

`
PHP Deprecated:  Return type of Osiset\BasicShopifyAPI\ResponseAccess::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/osiset/basic-shopify-api/src/ResponseAccess.php on line 60
`

`
PHP Deprecated:  Return type of Osiset\BasicShopifyAPI\ResponseAccess::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/osiset/basic-shopify-api/src/ResponseAccess.php on line 155
`

Issues & PRs in package:

https://github.com/gnikyt/Basic-Shopify-API/pull/129

https://github.com/gnikyt/Basic-Shopify-API/issues/136

https://github.com/gnikyt/Basic-Shopify-API/commit/d17d42ee109480c6fd3f969a53207ad14ebe2036

**Comment by Kyon147** [comment]
Hi @Lotuashvili 

The package needs to be updated to php8.0 as a minimum requirement for the api to be updated. it was planned before the original package was archived but i did not get a chance to sort all the tests and workflows in time.

It's on my list of things to do but if someone else wants to give it a go and submit a PR i'd be happy to take a look.

**Comment by itrack** [comment]
@Kyon147 , @Lotuashvili I don't think that renaming the namespace would be a good idea immediately, it would involve quite big updates for those using the package. Maybe only with a major version update

**Comment by Kyon147** [comment]
There's no plan to move to a new namespace yet but I will be updating the minimum requirement to 8.0 soon as we need to fix the dependency error and I was working on it before the package moved over.

**Comment by Kyon147** [comment]
This should be fixed now with the release of v18.0.0.

@Lotuashvili  Can you please test and close out this ticket if it is fixed.

**Comment by Kyon147** [comment]
Closing this out now as should be fixed with the release of `v18`
