### ISSUE TITLE
Form Redirect Issue

### ISSUE THREAD

**Issue by mehrabshah** [Kyon147/laravel-shopify#285]
<form action="{{route('setting.save')}}" method="post">

                            @csrf
                            <div class="form-group">
                                <input type="text" class="form-control session-token" name="instagram_user_name" value="{{$setting->instagram_user_name}}" id="instagram_user_name" {{($setting->instagram_user_name)?"readonly":"required"}}>
                            </div>
                            @if($setting->instagram_user_name)
                                <input type="hidden" name="disconnect" value="1">
                                <button type="submit" class="btn btn-danger float-right ">Disconnect Instagram Account</button>

                            @else
                                <input type="hidden" name="connect" value="1">
                                <button type="submit" class="btn btn-primary float-right ">Connect Instagram Account</button>
                            @endif
  </form> This is my Form code When clicking the 'Connect Instagram' button, it triggers my POST method, but it hangs without further redirects. I am using non-SPA pages

**Comment by Kyon147** [comment]
@mehrabshah have you read the session token wiki page? 

https://github.com/Kyon147/laravel-shopify/wiki/Authentication-Process

Forms won't submit if you don't pass the token and the `host` param.

**Comment by Kyon147** [comment]
Closing stale ticket. Reopen if you still have an issue.
