### ISSUE TITLE
Usage Charges Redirecting to Blank Page

### ISSUE THREAD

**Issue by koraysari** [Kyon147/laravel-shopify#288]
You can find the details related to this issue #278 

I utilized the URL::tokenRoute method to construct the usage charge link. The host parameter is now included in the URL. The newly generated link was as follows:

href="https://feedimize.fullyfeed.com/authenticate/token?shop=fully-feed.myshopify.com&target=https%3A%2F%2Ffeedimize.fullyfeed.com%2Fbilling%2Fusage-charge%3Fdescription%3DFive%2520e-mails%26price%3D1%26redirect%3Dhttps%253A%252F%252Ffeedimize.fullyfeed.com%26signature%3D0c7feec84b957578c5352e6ba3231fcfe4a3904096723558dcf0dfff1e7dd6df&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvZnVsbHktZmVlZA"

Unfortunately, even after implementing the usage charge link via the URL::tokenRoute, the issue persisted, leading to the same outcome of being redirected to a blank page without any visible error messages in the console.

![image](https://github.com/Kyon147/laravel-shopify/assets/26671350/eabeb819-fc2b-4670-8d9d-3d2891f0aa74)

**Comment by Kyon147** [comment]
Please dont open duplicate issues
