### ISSUE TITLE
help with warning on my logs

### ISSUE THREAD

**Issue by litalboa** [Kyon147/laravel-shopify#29]
i'm getting each job the following warning:
"Return type of Osiset\BasicShopifyAPI\ResponseAccess::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/forge/[priority.co.il/vendor/osiset/basic-shopify-api/src/ResponseAccess.php](http://edea.alembika.co.il/vendor/osiset/basic-shopify-api/src/ResponseAccess.php) on line 155"

V "^17.1"

can you please help me to solve it? do you know this warning?

**Comment by tinhphantrong0612** [comment]
Relate: https://github.com/Kyon147/laravel-shopify/issues/28

**Comment by Kyon147** [comment]
This was a known issue on the previous package, the fix is bumping the entire package to use `8.0` as a minimum requirement and then setting the basic-shopify-api to the right version.

It's something I need to do when I have the time.

**Comment by Kyon147** [comment]
Closing this as it is the same as #28
