### ISSUE TITLE
Installing on October or Winter CMS

### ISSUE THREAD

**Issue by baberuth22** [Kyon147/laravel-shopify#290]
When I run `composer require kyon147/laravel-shopify` in October CMS.

I get the following error 3 times:

`In ShopifyAppProvider.php line 320:`
                                                 
 `Class name must be a valid object or a string `

In winter CMS I can install without error, but if I turn on auto discovery I get the same error.

**Comment by Kyon147** [comment]
October CMS has not been tested with the package.

**Comment by Kyon147** [comment]
Going to close this, if someone wants to make it work we can open a new issue and PR
