### ISSUE TITLE
it requires api_key but now shopify uses oauth which is required client_id and client_secret so there us no more api_key. So how to get the access_token now?

### ISSUE THREAD

**Issue by alamgir-napollo** [Kyon147/laravel-shopify#294]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

Please describe the current behavior?

## Failure Information

Please help provide information about the failure if this is a bug.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
2. Step 2
3. ...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: vX.Y.Z
* Laravel Version: vX.Y.Z
* PHP Version: vX.Y.Z
* Template Engine: Blade or React
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Kyon147** [comment]
Hi @alamgir-napollo 

This package handles oauth for you. Once a store has installed your app the key is saved in the users table for that store.

I'd suggest reading the wiki so you can get a better idea of how it works.
