### ISSUE TITLE
issue 'Unable to verify signature.' where the HMAC signature sent by Shopify during authentication suddenly does not match

### ISSUE THREAD

**Issue by techbin** [Kyon147/laravel-shopify#295]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

I'm relatively new to app development and currently working on creating a Shopify app using Laravel 11. I've encountered an issue 'Unable to verify signature.' where the HMAC signature sent by Shopify during authentication suddenly does not match.

Despite attempting various troubleshooting steps such as clearing browser cache, installing on new stores, and verifying API and secret keys, I'm still facing this issue.

## Expected Behavior

Verify the signature & add the stores in the db and show the dashboard and allow billing

## Current Behavior

The system was working fine (Laravel 8.75 and laravel-shopify:17.4.3) and I was getting 'Unable to verify signature.' for only the "old stores" which was fine for me but after adding billing (enabled shopify payments and test gateways) - further made some transactions that failed. All the links in the app started having an issue. Unsure if this is an issue with Shopify or something else.

### Steps to Reproduce

Initially the system was Laravel 8.75 and "kyon147/laravel-shopify": "17.4.3" after started getting "Unable to verify signature." I upgraded my system to below configuration but the issue still exists.

Please provide detailed steps for reproducing the issue.
1. Install Laravel: 11
2. Install laravel-shopify: 21.0
3. Follow installation steps and access any route link

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* PHP Version: 8.2.16
* Laravel Version: 11.2.0
* Laravel Shopify: 21.0
* Template Engine: Blade

### Failure Logs

Please include any relevant log snippets or files here.
`
//Unable to verify signature.
Osiset \ ShopifyApp \ Http \ Middleware \ VerifyShopify : 96 handle
 // Verify the HMAC (if available)

        $hmacResult = $this->verifyHmac($request);

        if ($hmacResult === false) {

            // Invalid HMAC

            throw new SignatureVerificationException('Unable to verify signature.'); **** Error ****

        }

`

![Screenshot from 2024-04-09 10-12-38](https://github.com/Kyon147/laravel-shopify/assets/10051026/90147f38-f147-4298-9219-f1ef9c1e2843)

**Comment by frederickchan179** [comment]
I got the same issue recently :(

**Comment by HiteshPrivate** [comment]
add your credentials in .env file 
SHOPIFY_API_KEY
SHOPIFY_API_SECRET


- i forgot to add these that's why above error is coming after added my credentials it will works.

It's not the bug.

**Comment by Kyon147** [comment]
Closing as solution provided by @HiteshPrivate

**Comment by VivekShingala** [comment]
Getting same error even when .env file has proper values for 

SHOPIFY_API_KEY
SHOPIFY_API_SECRET

I have rotated the secret key
