### ISSUE TITLE
AfterAuthenticate Job and Script Tags Not Triggered Upon Reinstallation of App

### ISSUE THREAD

**Issue by thesunilyadav** [Kyon147/laravel-shopify#298]
*When a user uninstalls and then reinstalls the app, the installation process completes successfully, but it fails to execute post-installation tasks such as running the AfterAuthenticateJob and creating script tags.*

## Expected Behavior

The re-installation should go well without any problems

## Current Behavior

App was installed on this shop before. It was uninstalled and now trying to re-install again.
Here, app can be install successfully but it does not run the `AfterAuthenticateJob` and `scripttags` which I have set it up in `shopify-app.php` config file. However it setu ups the webhooks

## Failure Information

No error logs appear in the laravel.log file. Despite adding Log info to the first lines of both the construct and handle methods to monitor whether this job is running, no logs are being recorded anymore. This problem affects approximately 15-20 users in the live app and persists.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install the application.
2. Once the installation is successful, uninstall the application.
3. Now, reinstall the application and observe the creation of after_authenticate_job and script tags afterward.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: ^19.0
* Laravel Version: ^10.10
* PHP Version: ^8.1
* Template Engine: Blade
* Using a toolset (Docker, Laradock, Vagrant, etc.): N/A

### Failure Logs

No failure logs available.

Configuration inside shopify-app.php:

![image](https://github.com/Kyon147/laravel-shopify/assets/72142357/a2a6b8bb-0e73-4a93-b74b-d25bcb494261)

![image](https://github.com/Kyon147/laravel-shopify/assets/72142357/89b74dfc-01d2-4aa4-a5da-44a2008fc6fc)

**Comment by Kyon147** [comment]
@thesunilyadav 

I've tried to replicate this but could not - can you provide any more information.

**Comment by Kyon147** [comment]
Still not replicable, so closing - reopen if issue still happens

**Comment by forwells** [comment]
is any updates? I have a same issue
![image](https://github.com/user-attachments/assets/03d1b6a0-9fd5-4d2b-b134-02fdc069ad4a)

is not install this scripttag after install

**Comment by Kyon147** [comment]
@forwells can you provide more detail - PHP version, package version etc

**Comment by thesunilyadav** [comment]
Hi @Kyon147,

The `AfterAuthenticate Job` and `Script Tags` are now working fine for me.

@forwells, if you need to create script tags for all users, be sure to include all the `unacceptable_levels` in the `shopify-app.php` config file under the `theme_support` parameter. Here's an example:
![image](https://github.com/user-attachments/assets/3e5e5d34-b674-404e-80ea-788bf2260eaa)


Thanks,
Sunil
