### ISSUE TITLE
Deprecating of billing_on field on the UsageCharge resource

### ISSUE THREAD

**Issue by Msk101** [Kyon147/laravel-shopify#299]
Shopify's continuous updates underscore the deprecation of the 'billing_on' field within the UsageCharge resource. While some recommend temporarily resolving this by commenting out specific lines in ActivateUsageCharge.php (line 97) and Charge.php (line 102),

Can this solution be effective, considering my app combines usage-based functionality and monthly subscriptions? Please provide guidance on resolving this issue, as there are only a few months remaining.

Thank you.

**Comment by devRonak** [comment]
@Kyon147 can you please look into this issue?

**Comment by Kyon147** [comment]
@devRonak I won't be able to look at this for a few weeks, so happy for someone else to submit a PR in the meantime.

**Comment by Kyon147** [comment]
Closed as fixed in a PR
