### ISSUE TITLE
Let's make this package great. 

### ISSUE THREAD

**Issue by Hujjat** [Kyon147/laravel-shopify#3]
Hi everyone!

It's sad to see Tyler (the original maintainer) can't continue working on this package. I personally understand his situation. 

I'm not in a place to write this but someone should!

This package helped most of us build successful Shopify apps and generate over $1k MRR. Let's help @Kyon147 to maintain this package and improve it. 

We are all busy building our apps on top of this package but we shouldn't forget that the maintainer of the package needs support too. 

No more Ted talks!

If @Kyon147 continues maintaining this package, I'm happy to create new documentation with videos and easier step-by-step guides. 

We should clean up this package and remove unnecessary features/codes added over the past few years. 

Not required but if you're making a living from this package, it's good to give back by sponsoring the maintainer of this package.

Anyway, that's my suggestion. If you guys have any better recommendations, feel free to contribute. 

 Thank you @Kyon147 for taking the package responsibility. 
 
 Regards
 Hujjat

**Comment by Kyon147** [comment]
Thanks @Hujjat! I personally have used this package for years, so happy to try and keep it alive for my own apps and for the wider community to use. I plan to copy to copy the current wiki over when I have a mo but videos is a great idea. 

I think the direction of the package is going to need to move to support SPA exclusively. Blade templates are no longer a viable option if you want your package to be approved by Shopify because of their strict OAUTH process. Happy to hear some solutions/suggestions on keeping Blade, if we can make it compliant with Shopify's review process.

The other update with Tyler and I had in the works was making the package PHP8.X.X and up because of an issue with the Shopify api which needed to be upgraded from Tyler's other package.

One final big hurdle, if someone is willing, is to try and bring back `PER_USER` auth.

**Comment by Hujjat** [comment]
Great @Kyon147!

I have 1 app that uses blade files but works like SPA.  I learned it from this video https://laracasts.com/series/javascript-techniques-for-server-side-developers/episodes/1

I don't have experience building packages but I'm looking forward to learning and contributing to this package. 

And yes, `PER_USER` auth would be great to have.

**Comment by Kyon147** [comment]
> Great @Kyon147!
> 
> I have 1 app that uses blade files but works like SPA. I learned it from this video https://laracasts.com/series/javascript-techniques-for-server-side-developers/episodes/1
> 
> I don't have experience building packages but I'm looking forward to learning and contributing to this package.
> 
> And yes, `PER_USER` auth would be great to have.

Hey @Hujjat 

It would be interesting to get how you have Blade working like a SPA, I have not personally looked into it as I always just use VUE. So getting a guide up on how to use the blade route and seeing if that still passes validation would be good to know.

**Comment by dwimble** [comment]
> Hi everyone!
> 
> It's sad to see Tyler (the original maintainer) can't continue working on this package. I personally understand his situation.
> 
> I'm not in a place to write this but someone should!
> 
> This package helped most of us build successful Shopify apps and generate over $1k MRR. Let's help @Kyon147 to maintain this package and improve it.
> 
> We are all busy building our apps on top of this package but we shouldn't forget that the maintainer of the package needs support too.
> 
> No more Ted talks!
> 
> If @Kyon147 continues maintaining this package, I'm happy to create new documentation with videos and easier step-by-step guides.
> 
> We should clean up this package and remove unnecessary features/codes added over the past few years.
> 
> Not required but if you're making a living from this package, it's good to give back by sponsoring the maintainer of this package.
> 
> Anyway, that's my suggestion. If you guys have any better recommendations, feel free to contribute.
> 
> Thank you @Kyon147 for taking the package responsibility.
> 
> Regards Hujjat

Hi Hujjat, 

I'm trying to follow the instructions on the wiki.
I'm getting confused with the instruction on the other repo

Should I start with the following command to install Kyon147/laravel-shopify?
composer require osiset/laravel-shopify

When I do it says I should use this repo, but i'm not sure where to start?

**Comment by Kyon147** [comment]
> > Hi everyone!
> > 
> > It's sad to see Tyler (the original maintainer) can't continue working on this package. I personally understand his situation.
> > 
> > I'm not in a place to write this but someone should!
> > 
> > This package helped most of us build successful Shopify apps and generate over $1k MRR. Let's help @Kyon147 to maintain this package and improve it.
> > 
> > We are all busy building our apps on top of this package but we shouldn't forget that the maintainer of the package needs support too.
> > 
> > No more Ted talks!
> > 
> > If @Kyon147 continues maintaining this package, I'm happy to create new documentation with videos and easier step-by-step guides.
> > 
> > We should clean up this package and remove unnecessary features/codes added over the past few years.
> > 
> > Not required but if you're making a living from this package, it's good to give back by sponsoring the maintainer of this package.
> > 
> > Anyway, that's my suggestion. If you guys have any better recommendations, feel free to contribute.
> > 
> > Thank you @Kyon147 for taking the package responsibility.
> > 
> > Regards Hujjat
> 
> Hi Hujjat, 
> 
> I'm trying to follow the instructions on the wiki.
> I'm getting confused with the instruction on the other repo
> 
> Should I start with the following command to install Kyon147/laravel-shopify?
> composer require osiset/laravel-shopify
> 
> When I do it says I should use this repo, but i'm not sure where to start?

Hi @dwimble 

Now that it is a standalone package, please use 

`require kyon147/laravel-shopify`

and then follow the steps in the original wiki and normal.

I plan to move the wiki over but just not had the time at the mo.

Let me know if you run into issues.
