### ISSUE TITLE
Shopify API rate limit

### ISSUE THREAD

**Issue by RishabhTayal** [Kyon147/laravel-shopify#304]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

The package is supposed to handle the 2 api calls/sec api rate limit imposed by Shopify. In my project I still get the rate limit error sometimes.

## Current Behavior

Getting API rate limit error, specifically when APIs are called within a for loop.

Is there some extra configuration we need to do?

**Comment by Kyon147** [comment]
Rate limiting has always been a "rough" limit on the calls per second from what I remember when Taylor first implemented it as it is part of the Shopify-API package rather than this one directly. You should still do your own checks based on what you are getting back from Shopify too.
