### ISSUE TITLE
A couple weeks away.

### ISSUE THREAD

**Issue by Kyon147** [Kyon147/laravel-shopify#306]
Hey all,

Hope everyone is doing well.

I've been a little quieter than normal the last few weeks this is because we are expecting our first baby, and I'll likely be off from today (1st May 2024) for a couple weeks.

There's a lot of changes happening with Shopify and api upgrades etc for myself alone to keep on top of quickly. I am trying with what little time I have at the moment to progress through issues, questions, coding help, discord etc. 

I'd appreciate anyone who can also help look into issues and submit PRs - reviewing and deploying is a lot easier than trying to nail down an issue someone else has found and can re-produce and then look for a fix.

Happy coding and see you in a few weeks.

**Comment by sabira-khan** [comment]
Warm congratulations! @Kyon147

**Comment by d-shannon** [comment]
Congratulations @Kyon147!

**Comment by forwells** [comment]
Congratulations @Kyon147

**Comment by ignacio-dev** [comment]
Omg congratulations!! @Kyon147
