### ISSUE TITLE
Potential Bug: Session token is invalid

### ISSUE THREAD

**Issue by talktohenryj** [Kyon147/laravel-shopify#314]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

I expect to get the session token anytime someone uses the app. Most of the time I do get the session token but it seems on occasion I do not. 

## Current Behavior

I am not sure when or how it happens but because I don't have the session token I cannot run my code that checks if a user has my theme app extension on which is required for my app

## Failure Information

I don't have much more than I explained but the error is thrown on line 165 in the VerifyShopify file.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

I don't know how to reproduce as this happens pretty randomly it seems.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v19.2.0
* Laravel Version: v8.83.27
* PHP Version: v8.3
* Template Engine: Blade

### Failure Logs

![Screenshot 2024-05-16 at 3 59 05 PM](https://github.com/Kyon147/laravel-shopify/assets/88204834/4e7a0aea-b911-491d-98cb-0aad0558c3cb)

**Comment by Kyon147** [comment]
If you are using blade then the session token is gabbed by polling with some JS but it is not consistent always and is only a basic example.

If you wanted to look at a better way, interceptors in axios are a good idea.

**Comment by Kyon147** [comment]
I don't think this is a bug based on testing, but reopen if needed with more information
