### ISSUE TITLE
Redirection issue in Non Embedd shopify App

### ISSUE THREAD

**Issue by auspicious-soft** [Kyon147/laravel-shopify#330]
I have created a Shopify app with non embedded in Shopify admin. I have set the option from partner account embedded in Shopify admin False. But it gives the issue

## Expected Behavior

Redirect to the new tab with the app URL outside the Shopify admin after installation of the app.

## Current Behavior

App redirects to the Shopify admin panel and reload again and again.

## Failure Information

Reloading continuously.

### Context

* Package Version: 17.5
* Laravel Version: 8.75
* PHP Version: 7.3
* Template Engine: Blade 

Kindly help me to resolve this issue.

**Comment by Kyon147** [comment]
We don't support non-embed yet so going to close this issue.
