### ISSUE TITLE
Update the webhook URL

### ISSUE THREAD

**Issue by sandeeppangeni** [Kyon147/laravel-shopify#332]
I have setup the webhook and it was working on the development. I was using the ngrok on the local.
Now I have deployed the app to the server. 

**Issue: Now it is firing the webhook to the ngrok URL.**

![image](https://github.com/user-attachments/assets/ea1c881b-3f5a-4f72-8a46-98e48d2afbf1)

@michaellehmkuhl 
@ericnkatz 
@joelvh 
@onurkose 
@Jamesking56 

**Please help me with this.**

**Comment by Jamesking56** [comment]
@sandeeppangeni Don't just tag a bunch of people hoping to get your issue expedited

**Comment by onurkose** [comment]
@sandeeppangeni
Use Stackoverflow and/or Discussion section when searching solutions to your own problems.
It's not an issue of this repo.

**Comment by Kyon147** [comment]
As this is not an issue going to close @onurkose is right to mention stack or discussions.
