### ISSUE TITLE
How to use ui-nav-menu in blade ?

### ISSUE THREAD

**Issue by gofortiss** [Kyon147/laravel-shopify#334]
## How we can use ui-nav-menu ?

I am looking to add menu like : https://shopify.dev/docs/api/app-bridge-library/web-components/ui-nav-menu

But i can't find out how to implement it in blade ?

Do you have a solution ?

Thank you !

![navigation-menu](https://github.com/user-attachments/assets/76496a24-5091-41b8-9bdd-84016f7fe92c)

**Comment by gofortiss** [comment]
Here is the answer

**Comment by gofortiss** [comment]
`<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ \Osiset\ShopifyApp\Util::getShopifyConfig('app_name') }}</title>
        @yield('styles')
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="csrf_token" content="{{ csrf_token() }}" />
        <link href="{{ asset('assets/css/theme.min.css') }}" rel="stylesheet">
        
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
        <script src="https://unpkg.com/@shopify/app-bridge"></script>
        @stack('css')
        
        <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet">
        <ui-nav-menu>
  <a href="/" rel="home">Home</a>
  <a href="/templates">Templates</a>
  <a href="/settings">Settings</a>
</ui-nav-menu>
    </head>

    <body class="bg-light mb-10">
        <div class="app-wrapper">
            <div class="app-content container mt-4">
                <main role="main">
                    @yield('content')
                </main>
            </div>
        </div>

        @if(\Osiset\ShopifyApp\Util::getShopifyConfig('appbridge_enabled') && \Osiset\ShopifyApp\Util::useNativeAppBridge())
            <script src="{{config('shopify-app.appbridge_cdn_url') ?? 'https://unpkg.com'}}/@shopify/app-bridge{{ \Osiset\ShopifyApp\Util::getShopifyConfig('appbridge_version') ? '@'.config('shopify-app.appbridge_version') : '' }}"></script>
            <script
                @if(\Osiset\ShopifyApp\Util::getShopifyConfig('turbo_enabled'))
                    data-turbolinks-eval="false"
                @endif
            >
                var AppBridge = window['app-bridge'];
                var actions = AppBridge.actions;
                var utils = AppBridge.utilities;
                var createApp = AppBridge.default;
                var app = createApp({
                    apiKey: "{{ \Osiset\ShopifyApp\Util::getShopifyConfig('api_key', $shopDomain ?? Auth::user()->name ) }}",
                    host: "{{ \Request::get('host') }}",
                    forceRedirect: true,
                });
            </script>

            @include('shopify-app::partials.token_handler')
            @include('shopify-app::partials.flash_messages')
        @endif



        
        <script src="{{ asset('assets/js/script.js') }}"></script>
        @stack('js')
    </body>
</html>


`

**Comment by gofortiss** [comment]
Here is the answer 👍🏻 

```js
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ \Osiset\ShopifyApp\Util::getShopifyConfig('app_name') }}</title>
        @yield('styles')
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="csrf_token" content="{{ csrf_token() }}" />
        <link href="{{ asset('assets/css/theme.min.css') }}" rel="stylesheet">
        <!-- JavaScript -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
        <script src="https://unpkg.com/@shopify/app-bridge"></script>
        @stack('css')
        <!-- Optionally include additional CSS files -->
        <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet">

    </head>

    <body class="bg-light mb-10">
        <div class="app-wrapper">
            <div class="app-content container mt-4">
                <main role="main">
                    @yield('content')
                </main>
            </div>
        </div>

        @if(\Osiset\ShopifyApp\Util::getShopifyConfig('appbridge_enabled') && \Osiset\ShopifyApp\Util::useNativeAppBridge())
            <script src="{{config('shopify-app.appbridge_cdn_url') ?? 'https://unpkg.com'}}/@shopify/app-bridge{{ \Osiset\ShopifyApp\Util::getShopifyConfig('appbridge_version') ? '@'.config('shopify-app.appbridge_version') : '' }}"></script>
            <script
                @if(\Osiset\ShopifyApp\Util::getShopifyConfig('turbo_enabled'))
                    data-turbolinks-eval="false"
                @endif
            >
                var AppBridge = window['app-bridge'];
                var actions = AppBridge.actions;
                var utils = AppBridge.utilities;
                var AppLink = actions.AppLink;
                var createApp = AppBridge.default;

                var app = createApp({
                    apiKey: "{{ \Osiset\ShopifyApp\Util::getShopifyConfig('api_key', $shopDomain ?? Auth::user()->name ) }}",
                    host: "{{ \Request::get('host') }}",
                    forceRedirect: true,
                    
                });
                var homeLink = AppLink.create(app, {
                    label: 'Dashboard',
                    destination: '/',
                });

                var testLink = AppLink.create(app, {
                    label: 'test',
                    destination: '/test',
                });

                // Navigation Menu
                var NavigationMenu = actions.NavigationMenu;
                var navigationMenu = NavigationMenu.create(app, {
                    items: [homeLink, testLink]
                });
            </script>

            @include('shopify-app::partials.token_handler')
            @include('shopify-app::partials.flash_messages')
        @endif

        @yield('scripts')
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
        <!-- Optionally include additional JS files -->
        <script src="{{ asset('assets/js/script.js') }}"></script>
        @stack('js')
    </body>
</html>



```

**Comment by Ali-hammad-97** [comment]
hi @gofortiss

i am working on sales channel doing same as you were creating app-bridge using cdn! but my channel menu is still not showing up! 

App-bridge is creating and it is rediecting to our app! but menu is no here!
you know about any updates?
here is the code! 

Vue.blade.php file::
Html::
    <meta name="shopify-api-key" content="{{ config('sharedenv.api_key') }}" />
    <script src="https://unpkg.com/@shopify/app-bridge"></script>
Script::
document.addEventListener('DOMContentLoaded', () => {
            const createApp = window['app-bridge'].default;
            var actions = window['app-bridge'].actions;
            
            var AppBridge = window['app-bridge'];
            var AppActions = AppBridge.actions;
            console.log('AppActions');
            console.log(AppActions);
            var utils = window['app-bridge'].utilities;

            const Redirect = window['app-bridge'].actions.Redirect;

            const shopDomain = '{{ $shopDomain }}';
            const apiKey = '{{ config('sharedenv.api_key') }}';
            console.log('apikey from config');
            console.log('{{ config('sharedenv.api_key') }}');

            const app = createApp({
                apiKey: apiKey,
                host:  'ZGV2LXRlc3QyMi5teXNob3BpZnkuY29tL2FkbWlu',
                forceRedirect: true,
            });


            const itemsLink = AppActions.AppLink.create(app, {
            label: 'Items',
            destination: '/items',
            });

            const settingsLink = AppActions.AppLink.create(app, {
            label: 'Settings',
            destination: '/settings',
            });

            // create ChannelMenu with no active links

            const channelMenu = AppActions.ChannelMenu.create(app, {
            items: [itemsLink, settingsLink],
            });
            
 });

**Comment by aryankumarsundi** [comment]
@gofortiss i think this will not work for kyon147 package becouse the appBridge is not accessable here. but this will work on osiset package. 
If this is working in kyon147 package for anyone plz let me know.

Thanks in advance!!
