### ISSUE TITLE
Weird query coming from Shop.php

### ISSUE THREAD

**Issue by ignacio-dev** [Kyon147/laravel-shopify#338]
Using Laravel's debugbar, I see the following query being made on every request:

```sql
select * from `users` where `name` is null and `shopify_namespace` is null and `users`.`deleted_at` is null limit 1
```

It seems to be coming from this file:
```
vendor/kyon147/laravel-shopify/src/Storage/Queries/Shop.php
```

Is this normal?

**Comment by Kyon147** [comment]
It is likely the auth middleware needing to get the correct user to be able to use the API would be my guess without looking.

**Comment by Kyon147** [comment]
I believe it is normal from my memory unless you have more information. Going to close until there is more.
