### ISSUE TITLE
How do I need to create shopify checkout extensions using this laravel package ?

### ISSUE THREAD

**Issue by Ritesh-Rana** [Kyon147/laravel-shopify#343]
Currently my laravel project is running in the directory /mylaravel/

Do I need to create app under this directory ? and run generate extension cmd to create checkout extension ? 

Or is there any support that this laravel package can help ?

**Comment by Kyon147** [comment]
You should be able to use checkout extensions but there is an open PR that helps with the auth https://github.com/Kyon147/laravel-shopify/pull/329 

There is no guide at the moment on how to do it though but you can use the cli with this package no issue as I do on my apps.
