### ISSUE TITLE
Getting 404 on /authenticate after updating to v22.0.0

### ISSUE THREAD

**Issue by VivekShingala** [Kyon147/laravel-shopify#363]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

App installation should work and authenticate the shop

## Current Behavior

Getting 'There's no page at this address' on /authenticate 

## Failure Information

Uninstall webhook is working, but installation fails for new and existing shops with 404 error on Shopify store.

### Steps to Reproduce

1. Create new test shop or uninstall the app from the shop
2. Try to install the app
3. Authentication fails and Shopify throws 404 error
4. Latest version of this repo is used

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v22.0.0
* Laravel Version: 11.20.0
* PHP Version: 8.3.12
* Template Engine: Blade
* Using a toolset (Docker, Laradock, Vagrant, etc.): No (Nginx based server)

### Failure Logs

There are no errors related to this in the log file

![Screenshot 2024-11-15 at 4 34 16 PM](https://github.com/user-attachments/assets/adc9a1a4-0eba-4606-b8ee-63d4a9f8999e)
![Screenshot 2024-11-15 at 4 35 05 PM](https://github.com/user-attachments/assets/0c624040-b8a1-4ebe-826f-5c4448d62299)

**Comment by Ansari-techs** [comment]
I'm also facing this issue
<img width="1440" alt="Screenshot 2024-11-15 at 6 34 56 PM" src="https://github.com/user-attachments/assets/58f6e303-301e-47dc-b01e-22c200d0131e">

**Comment by jsalguero94** [comment]
I hadn't seen this topic open and commented on it in the PR. https://github.com/Kyon147/laravel-shopify/pull/361#issuecomment-2479821935

**Comment by jsalguero94** [comment]
Hey, I just created a fix that works for me. I hope it can help you guys

https://github.com/Kyon147/laravel-shopify/pull/364

**Comment by enmaboya** [comment]
I commented in the pull request, the issue was actually something else.

At the moment, this problem can be easily solved by:

Publishing the resources with php artisan vendor:publish
Editing the file resources/views/vendor/shopify-app/auth/fullpage_redirect.blade.php
Then, remove line #7.

https://github.com/Kyon147/laravel-shopify/pull/365

**Comment by VivekShingala** [comment]
Hi @jsalguero94 and @enmaboya 

Thank you for providing the quick fix. I tried with @enmaboya solution to remove a line from fullpage_redirect.blade.php and it worked.

Waiting for @Kyon147 to check and merge the PR and release it.

I will close this once the solution is released.

**Comment by CleytonBonamigo** [comment]
Just a contribution, it worked for me as well :).

**Comment by Kyon147** [comment]
The minor release with this fix is now out.

https://github.com/Kyon147/laravel-shopify/releases/tag/v22.0.1

**Comment by Kyon147** [comment]
Thanks @enmaboya for jumping on the fix quickly too 🙏
