### ISSUE TITLE
App keep loading after removing shopOrigin in 17.4.0

### ISSUE THREAD

**Issue by yasir-naseer** [Kyon147/laravel-shopify#37]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior
The app should load fine in Iframe after installation

## Current Behavior

When i install the app, the app keeps loading and im getting alot of error logs in console regarding app bridge

## Failure Information

I have setup a fresh shopify app, with the latest commit where shopOrigin was removed and other changes where made, but seems like when i install the app, the app keeps loading and im getting alot of error logs in console regarding app bridge

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install fresh laravel app
2. use the latest package version
3. Install the app

### Context

* Package Version: 17.4.0
* Laravel Version: 7.30.6
* PHP Version: 7.4.32
* Template Engine: Blade

### Failure Logs

![image](https://user-images.githubusercontent.com/58694913/210881704-103e7063-d79e-4559-8276-d474f2fd1887.png)
![image](https://user-images.githubusercontent.com/58694913/210881746-fdbe971b-7efa-4ea7-8dac-bee9fe101f0b.png)

**Comment by Kyon147** [comment]
Hi @yasir-naseer 

This can be fixed by moving to `17.4.1` as the issue was on the blade template version where the auth token redirect that happens never got the `host` param from the `VerifyShopify` middleware redirect.

**Comment by jackwefullfill** [comment]
hi @Kyon147 

so for now, blade templates still have to use shopOrigin right?

**Comment by Kyon147** [comment]
Hi @jackwefullfill 

`17.4.1` still uses `host` it just fixes a bug where it was not being passed through the auth properly. `shopOrigin` is no longer used as it is being deprecated by Shopify.

**Comment by jackwefullfill** [comment]
hi @Kyon147 , thanks for the explanation, so what I wanted to ask is that for the blade template, we need to wait for for 17.4.1 version in order to make the app compatible with new shopify domain right?

**Comment by Kyon147** [comment]
Yeah that is right, 17.4.1 will be compatible with the new admin domain but will also work for the older domain too.

**Comment by yasir-naseer** [comment]
hi @Kyon147 

after upgrading to 17.4.1. The issue of app not loading is fixed, since now im getting the host parameter in app bridge setup (which is all good now)

but when i redirect to some other page, the host parameter is lost again and the app starts keep loading, am i missing something?

Here is how my <a> tag look like

`<a class="nav-link" href="{{ \Illuminate\Support\Facades\URL::tokenRoute('home') }}" >Home</a>`

**Comment by Kyon147** [comment]
@yasir-naseer Shopify have explicitly said, if you are running a multipage app you need to manually pass the `host` param to all pages.

The package does not do this automatically, so you will need to remember to pass to `host` from page to page.
