### ISSUE TITLE
Not able to create webhooks on app installation 

### ISSUE THREAD

**Issue by developerzinan** [Kyon147/laravel-shopify#370]
I am trying to create webhook for my app which should create with app installation but its not working for some reason. My app was installed successfully and I can query data through api but webhook not created with my app.

## Current Behavior

The Webhooks is not being created while I am following the exact same steps as given in the package wiki, and not able to get to know the reason behind it please help me ASAP. The entry is going inside the job_failed table in the DB and payload showing something like this - `{"uuid":"c859e68b-edb5-4fa1-b5c3-30cb6975e883","displayName":"Osiset\\ShopifyApp\\Messaging\\Jobs\\WebhookInstaller","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"maxExceptions":null,"failOnTimeout":false,"backoff":null,"timeout":null,"retryUntil":null,"data":{"commandName":"Osiset\\ShopifyApp\\Messaging\\Jobs\\WebhookInstaller","command":"O:49:\"Osiset\\ShopifyApp\\Messaging\\Jobs\\WebhookInstaller\":2:{s:9:\"\u0000*\u0000shopId\";O:39:\"Osiset\\ShopifyApp\\Objects\\Values\\ShopId\":1:{s:6:\"\u0000*\u0000int\";i:9;}s:17:\"\u0000*\u0000configWebhooks\";a:1:{i:0;a:2:{s:5:\"topic\";s:15:\"PRODUCTS_UPDATE\";s:7:\"address\";s:68:\"https:\/\/completely-causal-jay.ngrok-free.app\/webhook\/products-update\";}}}"}}`

## Failure Information

When I run `php artisan queue:work` its showing like 

`2024-11-21 04:28:37 Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller ...................................... RUNNING`
`2024-11-21 04:28:38 Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller ................................ 216.26ms FAIL`

Screenshot: https://prnt.sc/1ucg_sbfuSgv , https://prnt.sc/IKj88CfRzZPW

### Steps to Reproduce

Followed the steps given in this page https://github.com/Kyon147/laravel-shopify/wiki/Creating-Webhook

### Context

Information about your setup. Using laravel herd and ngrok latest version

* Package Version: v22.0.1
* Laravel Version: v11.9
* PHP Version: v8.3
* Template Engine: Blade
* Using a toolset (Docker, Laradock, Vagrant, etc.): None

### Failure Logs

This is what I am getting in log file - 
`Exception: 1 in C:\Users\nadee\Herd\laraone\vendor\kyon147\laravel-shopify\src\Services\ApiHelper.php:521
Stack trace:
#0 C:\Users\nadee\Herd\laraone\vendor\kyon147\laravel-shopify\src\Services\ApiHelper.php(357): Osiset\ShopifyApp\Services\ApiHelper->doRequestGraphQL('\n        query ...', Array)
#1 C:\Users\nadee\Herd\laraone\vendor\kyon147\laravel-shopify\src\Actions\CreateWebhooks.php(68): Osiset\ShopifyApp\Services\ApiHelper->getWebhooks()
#2 [internal function]: Osiset\ShopifyApp\Actions\CreateWebhooks->__invoke(Object(Osiset\ShopifyApp\Objects\Values\ShopId), Array)
#3 C:\Users\nadee\Herd\laraone\vendor\kyon147\laravel-shopify\src\Messaging\Jobs\WebhookInstaller.php(60): call_user_func(Object(Osiset\ShopifyApp\Actions\CreateWebhooks), Object(Osiset\ShopifyApp\Objects\Values\ShopId), Array)
#4 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller->handle(Object(Osiset\ShopifyApp\Actions\CreateWebhooks))
#5 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Container\Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#7 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#8 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Container\Container.php(690): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#9 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#10 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(144): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#11 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#12 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller), false)
#14 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(144): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#15 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#16 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(123): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(71): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#18 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php(102): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#19 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(440): Illuminate\Queue\Jobs\Job->fire()
#20 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(390): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#21 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(334): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#22 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(148): Illuminate\Queue\Worker->runNextJob('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#23 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(131): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#24 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#25 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Container\Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#27 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#28 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Container\Container.php(690): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#29 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Console\Command.php(213): Illuminate\Container\Container->call(Array)
#30 C:\Users\nadee\Herd\laraone\vendor\symfony\console\Command\Command.php(279): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#31 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Console\Command.php(182): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#32 C:\Users\nadee\Herd\laraone\vendor\symfony\console\Application.php(1047): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 C:\Users\nadee\Herd\laraone\vendor\symfony\console\Application.php(316): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 C:\Users\nadee\Herd\laraone\vendor\symfony\console\Application.php(167): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(197): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 C:\Users\nadee\Herd\laraone\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1205): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 C:\Users\nadee\Herd\laraone\artisan(13): Illuminate\Foundation\Application->handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
#38 {main}`

**Comment by developerzinan** [comment]
@Kyon147 or anyone can help me ?

**Comment by enmaboya** [comment]
The issue is most likely in the code inside your webhook, as the data is being received. It fails on your side after starting queue:work.

**Comment by developerzinan** [comment]
Thanks for the reply @enmaboya , even if I install app uninstall webhook like the wiki 

`[
    'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'APP_UNINSTALLED'),
    'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', env('APP_URL') . 'webhook/app-uninstalled')
]`

`APP_URL=https://completely-causal-jay.ngrok-free.app/`

And there is no additional code or data inside AppUninstalledJob.php - 

`namespace App\Jobs;

class AppUninstalledJob extends \Osiset\ShopifyApp\Messaging\Jobs\AppUninstalledJob
{
}`

But still I got that error, Any idea ?

**Comment by developerzinan** [comment]
I uploaded my code in github, can anyone help to find out the issue please. - https://github.com/developerzinan/laraone/ @Kyon147

**Comment by enmaboya** [comment]
I ran your code, and it completes successfully, so the issue is either in some other code of yours (which you haven’t uploaded to GitHub) or in the working environment.
<img width="512" alt="image" src="https://github.com/user-attachments/assets/da8ac782-33e1-4115-932e-2d478e3cef91">

**Comment by developerzinan** [comment]
Yes, there was a issue with my working environment. I am using Windows PC and for localhost using wamp server. My default php path was pointed to wamp php.exe, so now I changed my php path from environment variables to laravel herd php.exe, Overall ok at this moment. Thanks a lot @enmaboya for testing.
