### ISSUE TITLE
navmenu component 

### ISSUE THREAD

**Issue by OmarFarukh17** [Kyon147/laravel-shopify#371]
navmenu component (@shopify/app-bridge-react@v4) How can we add this package to kyon147 package, can you help us with this? for LeftSider NavBar

**Comment by enmaboya** [comment]
the navigation panel is not related to this package, it is rendered using App Bridge, you can find the documentation [here](https://shopify.dev/docs/api/app-bridge-library/web-components/ui-nav-menu).

for the simplest implementation, add the code provided in the link above to your application's layout.

**Comment by Kyon147** [comment]
Closing this as it is not related to the package but there are some examples in the Discord for using the new appbridge v4.
