### ISSUE TITLE
when i multiple time click on left menu its give error session token invalid

### ISSUE THREAD

**Issue by ankitpatoliya3009** [Kyon147/laravel-shopify#372]
## Expected Behavior

expected behaviour is not get session token invalid error.

## Current Behavior

some time i get this error (need to change multiple times menu and you get some time token invalid error)

### Steps to Reproduce

1. Step 1 goto your app main page 
2. Step 2 multiple time chage menu from left side 

### Context

* Package Version: v22.0.1
* Laravel Versio: 11.*
* PHP Version: 8.2.*
* laravel + vuejs

### Failure Logs

![image (7)](https://github.com/user-attachments/assets/c8bc855e-c994-48fe-88bc-f0959dca2a2a)

**Comment by ankitpatoliya3009** [comment]
This issue comes because some times `window.axios.defaults.headers.common['Authorization']` this value is empty so axios not pass authorisation key in header.

**Comment by Kyon147** [comment]
If you are using blade then the default is to check every 2 seconds, so there can be an edge case where you are between valid tokens.

There's a couple of approaches to make it more robust, one of them is in the wiki using axios interceptors for example.
