### ISSUE TITLE
Don't work products webhook while work another webhooks

### ISSUE THREAD

**Issue by YunAltinus** [Kyon147/laravel-shopify#40]
## Expected Behavior

Work webhook product/create or product/update

## Current Behavior

Reads the order/create or customer/update but not read the product/create or product/update

## ScreenShots

![image](https://user-images.githubusercontent.com/62405204/211015634-4fe8cf6c-dbdd-4df3-a67f-6803bd1032ff.png)

### WebhookInstaller content
![image](https://user-images.githubusercontent.com/62405204/211016588-16da15b4-467d-418d-b7b6-809143fe7686.png)

* Package Version: ^17.3
* Laravel Version: ^9.19
* PHP Version: ^8.0
* Template Engine: Webpack - Vue
* Using a toolset: Docker, ngrok

**Comment by ZainSohail** [comment]
Can you provide the scopes you are using?

**Comment by YunAltinus** [comment]
I forgot to add the `read_products` :octocat:   Thanks for help 😄

**Comment by YunAltinus** [comment]
I forgot to add the read_products :octocat: Thanks for help 😄
