### ISSUE TITLE
Missing host after Billing approve redirect 

### ISSUE THREAD

**Issue by Tagra** [Kyon147/laravel-shopify#42]
## Failure Information

default.blade.php throwing error 
`app-bridge@latest:1 Uncaught s {name: 'AppBridgeError', message: 'APP::ERROR::INVALID_CONFIG: host must be provided', action: undefined, type: 'APP::ERROR::INVALID_CONFIG', stack: 'AppBridgeError: APP::ERROR::INVALID_CONFIG: host must be provided'}`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. SHOPIFY_FRONTEND_ENGINE is set to BLADE
2. Approving billing charge for new store 
3. Redirected to home route without host parameter

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v17.4.1
* Laravel Version: v8.75
* PHP Version: v8.0
* Using a toolset  Laradock

**Comment by Tagra** [comment]
After approve billing there is redirect to "/authenticate/token?" without host parameter

**Comment by Tagra** [comment]
@Kyon147 fix this and the beer is on me :beer:

**Comment by Kyon147** [comment]
Looking at the log, your using app bridge version 1.

Try moving to version 3 and check your config.

**Comment by Tagra** [comment]
App bridge is set to latest, i also tried manually to 2 but nothing changed.

App works just fine except after billing is approved, then it throws missing host error in javascript.

I think after Billing approval there is redirect to authenticate/token , and token function only sets
`[
                'shopDomain' => $shopDomain->toNative(),
                'target' => $cleanTarget,
 ]`

but token layout also includes @extends('shopify-app::layouts.default') which requires host

**Comment by Kyon147** [comment]
Is is the app install on load that is not working?

**Comment by Tagra** [comment]
1) Installing app - works fine
2) Redirected to accept payment
3) Accepting payment
4) Charge is accepted 
5) Redirected to /authenticate/token?shop=xxx&target=%2F and got javascript error about missing host

Now if i go back to app it works just fine, it is installed and charge is accepted. So and the end everything works, just that last redirect throwing JS error

**Comment by Kyon147** [comment]
That makes sense, I might have missed the host param passing when using auto install, I'll need to take a look and release a patch as the `billable` middleware might not be passing `host` on.

**Comment by Tagra** [comment]
:thumbsup:

**Comment by itrack** [comment]
+1  But on all pages 

{name: 'AppBridgeError', message: 'APP::ERROR::INVALID_CONFIG: host must be provided', action: undefined, type: 'APP::ERROR::INVALID_CONFIG', stack: 'AppBridgeError: APP::ERROR::INVALID_CONFIG: host must be provided'}

**Comment by itrack** [comment]
I re-added `shopOrigin: "{{ $shopDomain ?? Auth::user()->name }}",`
Now it works ok
It was deleted here https://github.com/Kyon147/laravel-shopify/commit/2f65f40999bef1ae6bbe6950540df4403a38f70a

**Comment by Kyon147** [comment]
It was removed intentionally as it will give you outdated app errors if you keep it in.

I'd recommend you remove it as it is no longer going to be supported by Shopify.

**Comment by itrack** [comment]
If I delete it, the application no longer works at first install, it remains in loading, with the error in the console:

{name: 'AppBridgeError', message: 'APP::ERROR::INVALID_CONFIG: host must be provided', action: undefined, type: 'APP::ERROR::INVALID_CONFIG', stack: 'AppBridgeError: APP::ERROR::INVALID_CONFIG: host must be provided'}

This is probably not the solution, but that works now, try to delete the application completely (from shopify store) and start with a fresh reinstall

**Comment by Kyon147** [comment]
Hey both,

Try upgrading to `17.4.2` https://github.com/Kyon147/laravel-shopify/releases/tag/v17.4.2 

This should be fixed in this version now, as host is being pass all the way through for the billable middleware now.

**Comment by Tagra** [comment]
Works like a charm :thumbsup:
Thanks for maintaining this repository !

**Comment by Kyon147** [comment]
@Tagra glad it works for you now and thanks for the appreciation 🙏
