### ISSUE TITLE
App doesn't load in Shopify admin

### ISSUE THREAD

**Issue by tager1199** [Kyon147/laravel-shopify#43]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

App loads in shopify admin

## Current Behavior

App stuck loading showing blank boxes.

## Failure Information

Errors in the Console: 
![image](https://user-images.githubusercontent.com/32684792/211543005-6d193e9b-1ad4-44a3-9a43-c247500ddbf3.png)
![image](https://user-images.githubusercontent.com/32684792/211543342-df7161ef-2d08-4ae1-8579-e866a35f7051.png)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install App on shopify store
2. Try to view app in store admin

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v17.4.1

### Failure Logs

Tried lots of debugging myself before resorting to reporting as an issue. It was working previously and then just seemed to stop working.
If I access it outside of shopify it redirects to:
https://[APP-URL]/authenticate/token?shop=[MYSTORE].myshopify.com&target=%2F
My web.php snippet:
```
Route::middleware(['verify.shopify'])->group(function () {
    Route::get('/', [WelcomeController::class,'index'])->name('home');
});
```

**Comment by Kyon147** [comment]
shopOrigin is no longer being used or passed through, so you should not be getting this error.

Have you extended the `default.blade.php` to make your own custom changes?

**Comment by tager1199** [comment]
Yes I have

**Comment by Kyon147** [comment]
You need to update your `default.blade.php` manually to match the latest version.

**Comment by tager1199** [comment]
As far as I can tell the ```default.blade.php``` is the most up to date version

**Comment by Kyon147** [comment]
it sounds like you are still passing `shopOrigin` in that blade file otherwise you would not get the error.

**Comment by itrack** [comment]
+1

{name: 'AppBridgeError', message: 'APP::ERROR::INVALID_CONFIG: host must be provided', action: undefined, type: 'APP::ERROR::INVALID_CONFIG', stack: 'AppBridgeError: APP::ERROR::INVALID_CONFIG: host must be provided'}

**Comment by Kyon147** [comment]
Going to close this ticket for now, let me know if you still are having issues.

**Comment by tager1199** [comment]
Hey I've fixed the issue, commenting here in case others have the same issue or if its useful to you. 
Compared my ```default.blade.php``` to another app that is working and it was missing this line on line 34
``` shopOrigin: "{{ $shopDomain ?? Auth::user()->name }}", ```
After adding that line in it works fine.

**Comment by Kyon147** [comment]
Hi @tager1199 that fix won't work long term.

`shopOrigin` will cause your app to be rejected and if the app is live, it will display a warning to Shopify store users. So it is not the right fix to implement.

**Comment by tager1199** [comment]
Thanks for the advice, I'll take a look.
