### ISSUE TITLE
App is not publishing because OAuth is not initiated at the correct URL

### ISSUE THREAD

**Issue by Basit-999** [Kyon147/laravel-shopify#49]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

OAuth to be initiated at https://app-security.myshopify.com/admin/oauth/authorize

## Current Behavior

OAuth is redirected to https://app-security.myshopify.com/admin/apps/b0d18f990014ba3d60db981a883a234a/authenticate/token

## Failure Information

Your primary app listing has 1 issue to fix before you can submit your app for review
**App must set security headers to protect against clickjacking.**
There was an error installing your app. The app must be installed to perform the security check. We expected OAuth to be initiated at https://app-security.myshopify.com/admin/oauth/authorize but were redirected to https://app-security.myshopify.com/admin/apps/b0d18f990014ba3d60db981a883a234a/authenticate/token. Your app must request installation immediately after clicking "add app." Apps must request shop access during installation, or reinstallation if the app was previously uninstalled from the shop. [Learn more about authentication in our developer documentation](https://shopify.dev/apps/store/requirements#a-authentication)
Please help provide information about the failure if this is a bug.

### Steps to Reproduce

1. Install the app to the store
2. Click on install unlisted app
3. Before and after Approv Payment

### Context

The app is authenticating, installing, charging, and that's all perfectly fine. For clickjacking the middleware I have added middleware and it shows fine but the problem actually is with the URL.
in web.php I have this route:
Route::get('/', [ShopifyController::class, 'home'])->middleware(['verify.shopify', 'billable'])->name('home');

* Package Version: 17.3
* Laravel Version: 8.75
* PHP Version: 7.4
* Template Engine: Blade

### Failure Logs

Please include any relevant log snippets or files here.
<img width="1146" alt="Screen Shot 2023-01-10 at 11 42 28 AM" src="https://user-images.githubusercontent.com/63302648/212254788-81084455-42c9-4404-b305-358fb0a6b358.png">

**Comment by Kyon147** [comment]
This is a known issue of using the blade template because Shopify are pushing for SPA.

You need to use Livewire or something similar to make your app function like a SPA.

**Comment by Basit-999** [comment]
Hey @Kyon147 It is not a multipage application. You can see the route in the details of the problem and that's the only route we have. We have a form but that works with Ajax. 
To be on the safe side, I have also implemented Livewire but It did not fix the problem. 
was that supposed to fix the error reported by Shopify?

**Comment by Kyon147** [comment]
@Basit-999 you are using the Template Engine: Blade which means your app is going to run as a multipage app. 

If you're using an SPA please change it to `REACT`

**Comment by Basit-999** [comment]
In REACT, should the authentication be done with Polaris(https://polaris.shopify.com) instead of how we currently do with this package?

**Comment by Kyon147** [comment]
@Basit-999 

The main auth is still handled by the package but you can handle the app bridge stuff with Polaris/React as that is what they recommend anyways.
