### ISSUE TITLE
App not loading

### ISSUE THREAD

**Issue by info3g** [Kyon147/laravel-shopify#60]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

App content needs to load successfully after successful installation.

## Current Behavior

App installed successfully. installed information stored in db successfully(Screenshot: https://prnt.sc/Jc5PJHqIFwgP)

But app not loading. Empty screen showing. Screenshot: https://prnt.sc/EqXk6FVuDOMo

I have checked console also and there is an error showing regarding @opentelemetry/api
Screenshot: https://prnt.sc/tP83fupt5UvK

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: 17.4
* Laravel Version: 7.0
* PHP Version: 7.4.33
* Template Engine: Blade

Please let me know what is causing. How I can make app loading successfully.

**Comment by info3g** [comment]
@Kyon147 could you please suggest the solution for the above issue?

**Comment by frexiz** [comment]
Do you have any errors in the chrome JS console?

**Comment by Kyon147** [comment]
Are you using the latest version of `17.4.4`

**Comment by info3g** [comment]
Yes I am using latest version

**Comment by info3g** [comment]
@frexiz  Yes, I have an error in console.
Error: @opentelemetry/api: Attempted duplicate registration of API: metrics
Screenshot: https://prnt.sc/tP83fupt5UvK

**Comment by Kyon147** [comment]
The new release should fix the issue on the redirect https://github.com/Kyon147/laravel-shopify/releases/tag/v17.4.3 

I've tied it into the token URL helper, so you don't need to pass host along with it anymore - it will pick it up from the current request as long as it exists.

 `<a href="{{ URL::tokenRoute('new-page', ['someparam' => 1]) }}">new page</a>`

**Comment by Kyon147** [comment]
Closing this one for now. Reopen if still an issue.

**Comment by info3g** [comment]
@Kyon147  Okay I am checking
