### ISSUE TITLE
Shop token is not generated @ shopify app installation

### ISSUE THREAD

**Issue by a-akashsoni** [Kyon147/laravel-shopify#62]
** I have setup my app on AWS Centos7. **

When I have authenticate the domain it gave the Osiset\ShopifyApp\Exceptions\MissingShopDomainException. Its working fine. But when I have installed the app on development store it did not generate the shop_token and app did not [installed.]
![Screenshot_16](https://user-images.githubusercontent.com/110217613/214017793-594072ac-24b5-4e1a-affc-5397dc295b7c.png)

(![Screenshot_1 (1)](https://user-images.githubusercontent.com/110217613/214017230-baf118e1-d9e6-4b9a-bebe-5457c297da92.png)).

Kindly resolve the issue as soon as possible.

Thanks

**Comment by Kyon147** [comment]
Hi @a-akashsoni what version of the app are you using as `shop_token` was the old stores DB table.

**Comment by Kyon147** [comment]
You should not have `shop_token` in your `users` table, so I would look at that - it does not seem like a package issue to me as a new install works fine.

Have you upgraded from a lower version?

**Comment by Kyon147** [comment]
Closing as it does not seem related to the latest package version.
