### ISSUE TITLE
Billable app error on install

### ISSUE THREAD

**Issue by dandyleon19** [Kyon147/laravel-shopify#63]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

App installed and user billed sucesfully

## Current Behavior

App gets installed but crashes at billing part with error

## Failure Information

This is the error

TypeError
Argument 1 passed to Osiset\ShopifyApp\Http\Controllers\BillingController::process() must be of the type int, object given, called in D:\Projects\shopify_acelerala_receipts_2.0\vendor\laravel\framework\src\Illuminate\Routing\Controller.php on line 54

![image](https://user-images.githubusercontent.com/48505581/214197263-ffcb68d3-fe36-41c9-9fd2-7f4dbd6c82b0.png)

**Steps to Reproduce**

1. Add plans using INSERT INTO plans (type,name,price,interval,capped_amount,terms,trial_days,test,on_install,created_at,updated_at) VALUES
('RECURRING','Test Plan',4.00,'EVERY_30_DAYS',10.00,'Test terms',7,TRUE,1,NULL,NULL);

2. Add middleware (['verify.shopify', 'billable']) to app home page route

3. Try installing the app

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Package Version: v17.4.2 (latest)
Laravel Version: v8.83.27
PHP Version: 7.4.20
Using a toolset (Docker, Laradock, Vagrant, etc.): none

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by joeelia** [comment]
I've totally seen this issue before. I forgot how I fixed it.

Do you have this in your .env?

`SHOPIFY_BILLING_ENABLED=1`

Because you need it. I think that might be the issue.

**Comment by dandyleon19** [comment]
Hi,
Yes, i have that in my .env

**Comment by dandyleon19** [comment]
The error path is "http://some-app/billing/process?shop=....", apparently the plan id is not being added in the URL.

Because i tried adding the plan id in the url like this "http://some-app/billing/process**/1**?shop=....", and it worked correctly.

I don't know what more i need to do.

**Comment by dandyleon19** [comment]
![image](https://user-images.githubusercontent.com/48505581/214366487-608bdc1d-ef31-4d1d-bf08-2961fea77efe.png)

**Comment by dandyleon19** [comment]
@Kyon147 

1. i added `SHOPIFY_BILLING_ENABLED=1` and `SHOPIFY_BILLING_REDIRECT="https://some-app/billing/process"` to .env file.
2. i added the `(['verify.shopify', 'billable'])` middlewares in my main route
3. i added the plan on database:

![image](https://user-images.githubusercontent.com/48505581/214367811-be3ac56c-0778-4616-87ac-30fa738e7c97.png)

I don't know what I'm missing to add. Please help me.

Thanks!!

**Comment by dandyleon19** [comment]
I fixed that removing `SHOPIFY_BILLING_REDIRECT="https://some-app/billing/process"` from the .env file

**Comment by joeelia** [comment]
Great, so you can close your issue then since it's resolved. @dandyleon19

**Comment by Kyon147** [comment]
Closing as this looks resolved now.
