### ISSUE TITLE
Webhook is not working

### ISSUE THREAD

**Issue by a-akashsoni** [Kyon147/laravel-shopify#64]
I have created the Orders Create webhook, but it does not working with handle method in laravel JOB. When I get info about webhook using info in handle function it does not show anything.

Kindly check the sample HTML of handle method for Orders Create JOB.
  `public function handle()
    {
        // Convert domain
        info($data);
        $this->shopDomain = ShopDomain::fromNative($this->shopDomain,$this-> data,$data);
        try{
            $shop = User::where('name', $this->shopDomain)->first();
            return;
        }
     
        catch(\Exception $e){
            Log::error($e->getMessage());
        }
     
        // Do what you wish with the data
        // Access domain name as $this->shopDomain->toNative()
    }`

Kindly check the issue and guide me to correct way to create and use webhook.

Thanks.

**Comment by Kyon147** [comment]
Please follow the wiki guide on setting up webhooks https://github.com/Kyon147/laravel-shopify/wiki/Creating-Webhooks

**Comment by a-akashsoni** [comment]
@Kyon147 Order Create webhook is not working. I already create webhook many times , but it does not respond anything. Kindly resolve this issue as soon as possible.

Thanks.
