### ISSUE TITLE
App Uninstall webhook is not working

### ISSUE THREAD

**Issue by a-akashsoni** [Kyon147/laravel-shopify#67]
I have created app uninstalled webhook. But it did not work after uninstall the app it did not add deleted _at value in users table.
Kindly check source code in Job.  
`public function app_uninstalled_job($shop) {

        try {

            $shop = User::where('name',$shop)->first();
            info($shop);
            
            PixelDetail::where('shop_id',$shop->id)->delete();
            PixelEvent::where('shop_id',$shop->id)->delete();
            PixelProduct::where('shop_id',$shop->id)->delete();
            
            $shop->delete();
            
            
            $dir = base_path().'/pull/'.$shop->name;
            
            $this->rrmdir($dir);
              
        }
        
        catch(\Exception $e) {
            
            Log::error($e->getMessage());
            
        }

    }
    
    public function rrmdir($dir)
    {
        if (is_dir($dir))
        {
             $objects = scandir($dir);
            
             foreach ($objects as $object)
             {
                   if ($object != '.' && $object != '..')
                   {
                        if (filetype($dir.'/'.$object) == 'dir') {rrmdir($dir.'/'.$object);}
                        else {unlink($dir.'/'.$object);}
                   }
             }
            
             reset($objects);
             
             rmdir($dir);
         }
    }`

Please check output Screenshot.

![Screenshot_17](https://user-images.githubusercontent.com/110217613/214283644-376747b7-4656-4db2-9bca-3fcfe0be9772.png)

Kindly resolve the issue.
Thanks

**Comment by a-akashsoni** [comment]
I have already use above commands to generate Uninstall job class , Job is created but webhook is not responding. Kindly check the JOB class code for uninstall.

`<?php namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Osiset\ShopifyApp\Objects\Values\ShopDomain;
use stdClass;
use App\User;
use App\PixelDetail;
use App\PixelEvent;
use App\PixelProduct;
use Log;
use File;


class AppUninstalledJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Shop's myshopify domain
     *
     * @var ShopDomain|string
     */
    public $shopDomain;

    /**
     * The webhook data
     *
     * @var object
     */
    public $data;

    /**
     * Create a new job instance.
     *
     * @param string   $shopDomain The shop's myshopify domain.
     * @param stdClass $data       The webhook data (JSON decoded).
     *
     * @return void
     */
    public function __construct($shopDomain, $data)
    {
        $this->shopDomain = $shopDomain;
        $this->data = $data;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        // Convert domain
        $this->shopDomain = ShopDomain::fromNative($this->shopDomain);
		$this->app_uninstalled_job($this->shopDomain->toNative() );

        // Do what you wish with the data
        // Access domain name as $this->shopDomain->toNative()
    }
	
	public function app_uninstalled_job($shop) {

        try {

            $shop = User::where('name',$shop)->first();
            info($shop);
            
            PixelDetail::where('shop_id',$shop->id)->delete();
            PixelEvent::where('shop_id',$shop->id)->delete();
            PixelProduct::where('shop_id',$shop->id)->delete();
            
            $shop->delete();
            
            
            $dir = base_path().'/pull/'.$shop->name;
            
            $this->rrmdir($dir);
              
        }
        
        catch(\Exception $e) {
            
            Log::error($e->getMessage());
            
        }

    }
    
    public function rrmdir($dir)
    {
        if (is_dir($dir))
        {
             $objects = scandir($dir);
            
             foreach ($objects as $object)
             {
                   if ($object != '.' && $object != '..')
                   {
                        if (filetype($dir.'/'.$object) == 'dir') {rrmdir($dir.'/'.$object);}
                        else {unlink($dir.'/'.$object);}
                   }
             }
            
             reset($objects);
             
             rmdir($dir);
         }
    }
}`

Kindly check and resolve the issue for webhook.

Thanks

**Comment by joeelia** [comment]
@a-akashsoni The code looks fine. Try sending a POST request to your uninstall webhook.

POST **https://(your-domain).com/webhook/app-uninstalled** and if the webhook is setup correctly then you will receive a `Invalid webhook signature.` 401 response because its just a blank webhook.

If you are getting this 401 response then try adding a log using the Log facade to your handle() function like this:
import the facade
`use Illuminate\Support\Facades\Log;`

Then in your handle() function, before the $this->app_uninstalled_job($this->shopDomain->toNative() ); add these lines:
```
Log::info('Webhook uninstall fired');
Log::info($this->shopDomain->toNative();
```

So you can check to see if the uninstall webhook is actually firing or not by checking your logs

**Comment by a-akashsoni** [comment]
@joeelia , I have tried it. But it does not create any log in the log file.

Thanks

**Comment by Kyon147** [comment]
Are you testing your webhooks locally? If you see in the wiki - webhooks are highly unreliable when testing locally and should ideally be done on a server.

You can use ngrok to make it a bit better, but I'd try on your actual server first.

Closing this as webhooks are working fine from testing locally using ngrok and on a dummy server.

**Comment by a-akashsoni** [comment]
@joeelia , I have tested its working on the WHM but on CentOS7 it did not work.

Thanks

**Comment by Kyon147** [comment]
Sounds like you have a set up issue on your centos server.

**Comment by a-akashsoni** [comment]
@Kyon147 every thing is working fine of this package on Centos7 except the webhook.

**Comment by a-akashsoni** [comment]
@Kyon147 every thing is working fine of this package on Centos7 except the webhook. Kindly give reference for the same.

Thanks.

**Comment by SergejSi** [comment]
I have the same problem. An order is created in the DB, but the handle method does not seem to be triggered.

**Comment by punitchawla19** [comment]
APP_UNINSTALLED webhook is not working with QUEUE_CONNECTION=database
But it's working fine with QUEUE_CONNECTION=sync

**Comment by sumantaakeans2020** [comment]
Its not working form me also, same problem. Also checked with QUEUE_CONNECTION=sync

**Comment by VivekShingala** [comment]
HI @a-akashsoni / @sumantaakeans2020 

Were you able to manage to fix the issue? I'm facing the same issue.

**Comment by VivekShingala** [comment]
> HI @a-akashsoni / @sumantaakeans2020
> 
> Were you able to manage to fix the issue? I'm facing the same issue.

Please ignore the above comment. I was able to fix it by looking into the Exception trace in failed_jobs table. All good with the app uninstall job now.

**Comment by kashyap-rock** [comment]
Hello @Kyon147 I have setup laravel 12 with kyon147/laravel-shopify v23.1.0 in my local and used ngrok tunnel url. App is connected successfully connected app but not able to trigger AppUninstalledJob to delete user data on app uninstall.
Used Reference : [wiki](https://github.com/Kyon147/laravel-shopify/wiki/Installation#uninstalled-job-recommended)
