### ISSUE TITLE
Embbedd App Not Loading Status 302

### ISSUE THREAD

**Issue by info3g** [Kyon147/laravel-shopify#68]
## Expected Behavior
App needs to load successfully. App welcome contents need to load successfully.

## Current Behavior
App installed successfully. Not loading in shopify admin. Blank screen showing.

In console->Networks -screenshot:  https://prnt.sc/CL4sN2d1PgtY
Header showing status 302. 

Package Version: 17.4.3
Laravel Version: 8.0
PHP Version: 7.4.33
Template Engine: Blade

It's urgent. Please let me know why I am getting this issue. I am using latest version of kyon package.

**Comment by joeelia** [comment]
This is expected as you are supposed to have a 302 redirect on that route then right after you will have a route with URL param of 'token' that will return a 200 response. And I see that token route in your screenshot. If you scroll down a little bit more I'm guessing there will be another 200 response for the same URL you took a screenshot of.

The reason why you are seeing a blank screen might be that you haven't imported your blade files correctly.

Is this a new app or is it existing?

@info3g

**Comment by info3g** [comment]
@joeelia  It's a new app

**Comment by info3g** [comment]
@joeelia  It's a fresh installation

**Comment by info3g** [comment]
@joeelia I can  share the zip folder if you want?

**Comment by joeelia** [comment]
@info3g Yeah, send me the zip folder. You can join the Discord https://discord.gg/rUwAteUqCN

**Comment by info3g** [comment]
@joeelia ok

**Comment by info3g** [comment]
@joeelia https://drive.google.com/file/d/1JYOMVGhSy6QYdpMV3qxjzRk0-a3a5WRP/view?usp=share_link

App zip link. Please see zip here

**Comment by joeelia** [comment]
For anyone else reading this I was able to get this working by downloading the .zip file and all I did was a migration + add Shopify API keys in .env

Unfortunately, OP is still having issues. Most likely machine specific.

**Comment by Kyon147** [comment]
This does not look like a package issue, as I can also set up a new app on the latest version fine.

Closing this, if you need specific help message in the discord and someone might be able to.
