### ISSUE TITLE
Shopify Embeded app redirection not working with laravel-shopify latest

### ISSUE THREAD

**Issue by slashcart** [Kyon147/laravel-shopify#70]
I am facing an issue while converting app from Osiset 16 to latest 17.4. I created new Laravel project then installed latest osiset and put my existing resources, controllers , models and etc. in new version functionality is working ok but its not redirecting the page to other when  click on link in app or when middleware redirects  user to procong page it keep showing skelton and page never loads. I am using blade as frontend engine. I checked there is no server side error

**Comment by Kyon147** [comment]
Thi @slashcart 

The new version needs `host` to be passed with every request - if you are just seeing the skeleton page that suggests it is missing the `host` param in the url. 

You can use the helper as it will pass it on automatically. 

<a href="{{ URL::tokenRoute('new-page', ['someotherparam' => 1]) }}">My new page</a>

**Comment by slashcart** [comment]
Hi @Kyon147  thanks for your response. I will try this.

**Comment by slashcart** [comment]
Thanks my problem resolved.

**Comment by slashcart** [comment]
Hi, @Kyon147 sorry but it worked yesterday but today its not working again

**Comment by Kyon147** [comment]
@slashcart if it worked yesterday, it sounds like you have a set up issue rather than a package one.

Without knowing more about your set up and the code it's hard to know.

**Comment by slashcart** [comment]
ok no worries I will look in to it

**Comment by Kyon147** [comment]
Going to close this again for now, as my new app which I set up this morning to test issues is not showing an issue like this but there is a bug that is open if you have billing enabled as well. You might be running into this issue, so try it with billing `false` for now.
