### ISSUE TITLE
No authenticated user or shop domain 

### ISSUE THREAD

**Issue by Rajdev2011** [Kyon147/laravel-shopify#71]
I have created a payment gateway app using your package.

when merchants install the app we are showing a form to fill the pg keys .

App is working is all desktop browsers and even in apple safari too.But In IOS devices iam getting issue "No authenticated user or shop domain" 

Iam using 17.1 version.

if iam updating to 17.4 then form is not submiting in the browsers too.

**Comment by Rajdev2011** [comment]
I upgraded to 17.4 now and desktop is also working 

but ios having same issue

**Comment by Kyon147** [comment]
Hi @Rajdev2011 

Are you using blade templates?

**Comment by Rajdev2011** [comment]
Yes iam using bloade templates

**Comment by Kyon147** [comment]
@Rajdev2011 I've tested this on my iPhone and it worked fine. 

Sounds like you are upgrading an existing app, so you might be missing something in your codebase.

**Comment by Kyon147** [comment]
Going to close this for now, as I could not replicate it on an iOS device.

**Comment by Rajdev2011** [comment]
should i remove old  pacakage and install new one how we can upgrade presently i relaced the files of SRC

**Comment by Kyon147** [comment]
You should update your composer.json to point to the new package.

**Comment by Rajdev2011** [comment]
ok thank you

**Comment by droplogicx** [comment]
I'm using version 19.1 of the package but I'm facing "No authenticated user or shop domain" problem on Safari browser, can you help me?
