### ISSUE TITLE
Double Host Param Causing Issues on Auth Routes

### ISSUE THREAD

**Issue by joeelia** [Kyon147/laravel-shopify#73]
## Expected Behavior

Auth route to have only one URL GET Param of 'host'

The fix would be to ensure only one **host** param is ever sent on any route within this package

## Current Behavior

Currently, as of v17.4.2 and up there seems to be 'host' URL Param in the authenticate routes twice thus causing issues with decoding the 'host' param into the blade component.

## Failure Information
Notice the two **host** params
<img width="528" alt="Screen Shot 2023-01-30 at 7 05 31 PM" src="https://user-images.githubusercontent.com/44442621/215672142-d6b14d03-aafe-425d-ae7a-dd6f8ef04449.png">

Notice the type error here which is the same **host** param twice:
<img width="1259" alt="Screen Shot 2023-01-30 at 9 04 35 PM" src="https://user-images.githubusercontent.com/44442621/215671279-40779aa2-43aa-4b2a-9ded-0c28d749c9e6.png">

### Steps to Reproduce

- Have 17.4.2 or above app version
- Test in production (works fine on localhost)
- Make sure the environment **SHOPIFY_FRONTEND_ENGINE=BLADE**
- Have an app that has a charge you need to approve
- Make sure you have billable middleware
- Load any page and see error

Note: This might not be applicable for SPA's

### Context

See steps to reproduce above

### Failure Logs

See Failure Information

### THE TEMP FIX

I was able to fix this through the app.blade.php by just using this code for the host

```
 var app = createApp({
      apiKey: "{{ \Osiset\ShopifyApp\Util::getShopifyConfig('api_key', $shopDomain ?? Auth::user()->name ) }}",
      host: "{{ is_array(\Request::get('host')) ? \Request::get('host')[0] : \Request::get('host') }}",
      forceRedirect: true,
});
```

**Comment by d-shannon** [comment]
I confirm having same issue moving from 17.2 to 17.3

**Comment by joeelia** [comment]
This repo recreates the issue. Its Vanialla Laravel and Laravel Shopify (this package): https://github.com/joeelia/example-shopify-host-issue

I noticed when I use the default welcome.blade.php the issue does not exist, but when I use the custom app.blade.php the issue happens.

I will make a video and write more details later today or tomorrow but all you need to do is:

1. Clone the repo
2. Put in your API keys
3. Migrate database with `php artisan migrate:refresh --seed` prepopulates the plans table
4. Install app, approve charges and check the HTTP logs for one of the GET requests that contains two 'host' params

**Comment by Kyon147** [comment]
Hey @joeelia 

Thanks for this, it is a bug when you have blade + billing enabled. It looks like the new changes to make sure `host` is passed through `authenticate/token` is adding it twice.

**Comment by Kyon147** [comment]
Hey @joeelia 

Can you try my new change locally https://github.com/Kyon147/laravel-shopify/pull/76 and see if the issue is fixed for you.

You can set your composer to this branch specifically and update to use the code base at that point.

**Comment by Kyon147** [comment]
Hey @joeelia any luck with the new PR?

**Comment by d-shannon** [comment]
Hey @Kyon147, If you have time, would it be possible to tag a new release?

**Comment by Kyon147** [comment]
I have pushed a new tag https://github.com/Kyon147/laravel-shopify/releases/tag/v17.4.4

**Comment by d-shannon** [comment]
> I have pushed a new tag https://github.com/Kyon147/laravel-shopify/releases/tag/v17.4.4

Much appreciated! Thank you
