### ISSUE TITLE
I have updated the package  ^17.3 to ^17.4. AppBridgeError causing issues

### ISSUE THREAD

**Issue by secureweb16** [Kyon147/laravel-shopify#74]
https://prnt.sc/wqQd69wLlisf
https://prnt.sc/zoqZA4f-OPwb

**Comment by anjalihooda** [comment]
I'm using blade templates

**Comment by secureweb16** [comment]
I'm using blade templates

**Comment by Kyon147** [comment]
It sounds like the app is not getting the `host` param at all. 

Is this a fresh install?

**Comment by Kyon147** [comment]
Closing this for now until further info is provided.
