### ISSUE TITLE
App Not Loading In Admin.Shopify.Com Its Showing Outdated Error When Opened In Admin.Shopify.Com

### ISSUE THREAD

**Issue by anjalihooda** [Kyon147/laravel-shopify#75]
i have developed a shopify app using (https://github.com/Kyon147/laravel-shopify )library in laravel its working perfectly in normal admin's which are not using admin.shopify.com but in admin.shopify.com its showing that this app is outdated. Due to which its not getting approved for shopify app store. 
do any one have solution for this ?

https://prnt.sc/9WZuyFLwSF6R

**Comment by RishabhTayal** [comment]
same here.

**Comment by Kyon147** [comment]
I've seen a couple of these reports now, so I thought I would set up a new app and use my admin.xxxx store.

I have set up on Blade, working fine from what I can see.

![image](https://user-images.githubusercontent.com/32519106/215983277-e5b78014-bb50-4ec2-a6a0-0e68714c39a4.png)

No issues on the auth or on the initial load. 

So I'll need some more information from people with the issue about their code base. 

- Is it a completely new install or an upgrade
- What version are you using?
- What is your technical stack, i.e local / staging and what is the server specs CentOS / Nginx / Apache etc?
- Are you using the Blade version or REACT one.

**Comment by LonnyX** [comment]
@Kyon147 If you want to reproduce the issue you should use the new shopify domain: `https://admin.shopify.com/store/{yourTestShop}`

See more info here: https://shopify.dev/changelog/updates-required-for-embedded-apps-to-work-on-the-new-shopify-admin-domain

**Comment by Kyon147** [comment]
@LonnyX the test was on the new domain.

**Comment by Kyon147** [comment]
I have noticed when debugging the auth routes, that Shopify also shows this error if the app does not load in X amount of seconds.

The main issue for the error is usually either]
- `shopOrigin` is still in your AppBridge create in `default.blade.php`
- There is an issue with your iframe security policy and `admin` etc is not set as the ones allowed to load. 

I've tried to reproduce this error over and over on a new install and cannot. 

Closing this for now but open it again if you have more information or a repo that I can use to replicate the issue locally.

**Comment by Kyon147** [comment]
I've noticed an issue in chrome based browsers that might not be package related - sometimes Chrome decides to block the window.top redirect used for billing as it treats it as a popup. 

If you see this issue where you have billing enabled but it is going to a blank screen, check that chrome has not blocked anything.
