### ISSUE TITLE
v12 redirect to full page because of "Shopify App Outdated" 

### ISSUE THREAD

**Issue by APdevelopments** [Kyon147/laravel-shopify#78]
I'm using version 12.1 and because I need some time to migrate to v17, I decide to build full page app - non embedable.

To redirect full page I disable AppBridge from Shopify-app.php config file and also I remove AppBridge code from blade templates but when I start app it show inside Shopify dashboard as iframe.

How I can redirect to full page and I do not want to change version?

**Comment by APdevelopments** [comment]
The temporary solution is to disable AppBridge and Embeded app in Shopify dashboard

**Comment by Kyon147** [comment]
As @APdevelopments mentions, you need to do those two things.

I would like to get non-embed back into the package for the next version - so if you do work on it could you also open a PR?

Going to close this ticket off for now as it is for an older version.
