### ISSUE TITLE
I have updated the package ^17.3 to ^17.4. AppBridgeError causing issues

### ISSUE THREAD

**Issue by anjalihooda** [Kyon147/laravel-shopify#79]
I have used laravel Blade template, and it's working fine on ^17.3 But on this version, I'm facing the outdated issue, Then I will update to the new version ^17.4 then this error occur please let me know where is the problem, 

https://www.loom.com/share/1f3c80b28e2340088ea7b57bd3ca142a

**Comment by anjalihooda** [comment]
I have tried to remove the (SHOPIFY APP BRIDGE VERSION=3.0) this line from ENV then errors does not occur but it will not redirect to the other pages.

https://prnt.sc/pzN0e7FU0Xnr

https://prnt.sc/geTg7yKxeG0C

**Comment by anjalihooda** [comment]
First time home is load perfectly, When I click on test route it is not redirect to the route or and showing any error.


Route::group(['middleware' => ['verify.shopify']], function () { 

    Route::get('/', function () {
         return view('welcome');
    });

   Route::get('/test', function () {
        return view('test');
    });
});


Please confirm route structure is correct or not if not then please provide the route structure how to manage it.

**Comment by bhargavcsweb** [comment]
Yes i also get same issue

**Comment by Kyon147** [comment]
@anjalihooda - Is this a new install? 

I've updated one of my older apps this morning, and removing the `shopOrigin` from my overwritten template works perfectly.

If you are getting this error there is a place in your codebase that has shopOrigin still or you are missing host in the app bridge init.

**Comment by bhargavcsweb** [comment]
Hello @Kyon147 

can you please send me the sample code of app bride and overwritten template and path also that will help

**Comment by Kyon147** [comment]
It's all in the package files https://github.com/Kyon147/laravel-shopify/blob/master/src/resources/views/layouts/default.blade.php

**Comment by Kyon147** [comment]
Golng to close this ticket for now, as I can't replicate the issue - so reopen when you have more information for me to be able to debug on a test repo please.

**Comment by anjalihooda** [comment]
Thanks so much @Kyon147
