### ISSUE TITLE
Fulfillment Webhook is not working

### ISSUE THREAD

**Issue by a-akashsoni** [Kyon147/laravel-shopify#80]
I have created two webhook. 1.) Fulfillment Create Webhook and 2.) Fulfillment Update Webhook . But when I create a order in shopify store and info the data of fulfillment create JOB. I did not get response from the webhook. In log file it shows nothing.

Here is the code of Job handle function for the reference.
`public function handle()
    {
        info($data);
        
        // Convert domain
        $this->shopDomain = ShopDomain::fromNative($this->shopDomain,$this-> data,$data);
       try{
        $shop = User::where('name', $this->shopDomain)->first();
        }
        catch(\Exception $e){
            Log::error($e->getMessage());
        }
       
       
        // Do what you wish with the data
        // Access domain name as $this->shopDomain->toNative()
    }`

Kindly help me to resolve the issue as soon as possible.
Thanks.

**Comment by Kyon147** [comment]
Are you testing locally? As mentioned in the wiki https://github.com/Kyon147/laravel-shopify/wiki/Creating-Webhooks#webhook-requirements they are highly inconsistent when testing locally.

**Comment by a-akashsoni** [comment]
@Kyon147 , I am testing on the server. But its response is null. Kindly help me why the webhooks are not give response on the server. Kindly revert on this as soon as possible. so we can resolve the issue and run the webhooks on the server.

Thanks.

**Comment by Kyon147** [comment]
@a-akashsoni I'll need more information to help you.

Can you link me to your codebase so I can see your set up.

**Comment by a-akashsoni** [comment]
@Kyon147 you can check the webhooks in config.php. Code is below for webhook in config.php.

 `'webhooks' => [
        /*
            [
                'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'ORDERS_CREATE'),
                'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', 'https://some-app.com/webhook/orders-create')
            ], [
                'topic' => env('SHOPIFY_WEBHOOK_2_TOPIC', 'APP_PURCHASES_ONE_TIME_UPDATE'),
                'address' => env('SHOPIFY_WEBHOOK_2_ADDRESS', 'https://some-app.com/webhook/purchase'),
            ]
            ...
        */
        
            [
                'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC','FULFILLMENTS_CREATE'),
                'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS','https://shipping-carrier.auspicioussoft.com/webhook/fulfillments-create')
            ],
            [
                'topic' => env('SHOPIFY_WEBHOOK_2_TOPIC','FULFILLMENTS_UPDATE'),
                'address' => env('SHOPIFY_WEBHOOK_2_ADDRESS','https://shipping-carrier.auspicioussoft.com/webhook/fulfillments-update')
            ],


    ],`
    
You can check the whole code for fulfillment Create Job is below. Kindly check the code for Job also.

`<?php namespace App\Jobs;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Osiset\ShopifyApp\Objects\Values\ShopDomain;
use stdClass;
use App\User;
use Log;

class FulfillmentsCreateJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Shop's myshopify domain
     *
     * @var ShopDomain|string
     */
    public $shopDomain;

    /**
     * The webhook data
     *
     * @var object
     */
    public $data;

    /**
     * Create a new job instance.
     *
     * @param string   $shopDomain The shop's myshopify domain.
     * @param stdClass $data       The webhook data (JSON decoded).
     *
     * @return void
     */
    public function __construct($shopDomain, $data)
    {
        $this->shopDomain = $shopDomain;
        $this->data = $data;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        info($data);
        
        // Convert domain
        $this->shopDomain = ShopDomain::fromNative($this->shopDomain,$this-> data,$data);
       try{
        $shop = User::where('name', $this->shopDomain)->first();
        }
        catch(\Exception $e){
            Log::error($e->getMessage());
        }
        // Do what you wish with the data
        // Access domain name as $this->shopDomain->toNative()
    }
}`    

Kindly check the code and revert on the same as soon as possible.

Thanks.

**Comment by Kyon147** [comment]
![image](https://user-images.githubusercontent.com/32519106/216605370-99ef7215-c534-4144-89c8-d352fc74fe37.png)

It looks like you are using the same name`SHOPIFY_WEBHOOK_1_TOPIC` for both orders create and the FULFILLMENTS_CREATE. If you have this ENV you are going to confuse the webhook creation. 

Does the order create webhook work?

**Comment by Kyon147** [comment]
I try a different webhook to see if it is an issue with the fulfilment ones.

**Comment by a-akashsoni** [comment]
@Kyon147 , Is different webhook is working properly.

**Comment by a-akashsoni** [comment]
@Kyon147 I have shared Job handle function code with you. when I run info($data) command , it does not show anything.
Kindly check the issue help me to resolve the issue.

Thanks.

**Comment by a-akashsoni** [comment]
@Kyon147 Any update on this issue ?
