### ISSUE TITLE
when I uploading multiple file Images throw axios request then it take time and request genrate error (403 session token has been expired)

### ISSUE THREAD

**Issue by abubakar0101** [Kyon147/laravel-shopify#81]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

Please describe the current behavior?

## Failure Information

Please help provide information about the failure if this is a bug.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
2. Step 2
3. ...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: vX.Y.Z
* Laravel Version: vX.Y.Z
* PHP Version: vX.Y.Z
* Template Engine: Blade or React
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Kyon147** [comment]
Closing this as the issue template is not complete.

Also for non-package issues please use the discussion section or the Discord.
