### ISSUE TITLE
Force approval of new API scopes

### ISSUE THREAD

**Issue by CedricVleminckx** [Kyon147/laravel-shopify#88]
## Expected Behavior

When adding new scopes to the api_scopes list the app must go to the approval page of these new scopes.

## Current Behavior

After adding scopes we do not see the approval page for the new scpoes.

### Steps to Reproduce

1. Install app in development store and accept initial scopes
2. Add new scopes in the config file
3. Open the app again

### Context

I was also trying to force the user to go through authentication again to accept the new scopes. However then the app fails on the full_page_redirect.blade.php file. Right now I get the error that the host parameter is required to config AppBridge.
To force the redirect I made a middleware that checks if the users has to approve new scopes. It then deletes it password and redirect it to the authentication page.
```php
$user = User::where('name', $request->get('shop'))->first();

if (isset($user->scope_approval_required) && $user->scope_approval_required) {
    $user->scope_approval_required = 0;
    $user->password = '';
    $user->save();

    return redirect()->route(Util::getShopifyConfig('route_names.authenticate'), ['shop' => $user->name]);
}

return $next($request);
```

* Package Version: v17.4.3
* Laravel Version: v8.0
* PHP Version: v8.0
* Template Engine: React
* Using a toolset (Docker, Laradock, Vagrant, etc.): Valet

**Comment by CedricVleminckx** [comment]
I fixed it by not removing the user password and adding the host to the redirect
```php
$user = User::where('name', $request->get('shop'))->first();

        if (isset($user->scope_approval_required) && $user->scope_approval_required) {
            return redirect()->route(
                Util::getShopifyConfig('route_names.authenticate'),
                [
                    'shop' => $user->name,
                    'host' => $request->get('host')
                ]
            );
        }

        return $next($request);
        ```

**Comment by d-shannon** [comment]
Hey @CedricVleminckx,

The process of redirecting the user via authentication aproves the new scopes or should something be presented to the user?

Cheers!

**Comment by CedricVleminckx** [comment]
Hi @d-shannon 
I was trying to force users to go through authentication, so that they would have to accept the new API scopes.
When they have to accept new scopes, Shopify presents them with an "Update app" screen. 

All works well now.

**Comment by d-shannon** [comment]
> Hi @d-shannon I was trying to force users to go through authentication, so that they would have to accept the new API scopes. When they have to accept new scopes, Shopify presents them with an "Update app" screen.
> 
> All works well now.

Thanks, got working myself too. Thanks for that

**Comment by yadsgroup** [comment]
Hi @CedricVleminckx,

I tried to implement your solution in a middleware but it didn't work for me. I can see in Inspector->Network that my request should redirect (HTTP 302) but my app won't make the redirection.

Can you see something wrong in my code below?

```
class EnsureShopifyScopes
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure(\Illuminate\Http\Request): (\Illuminate\Http\Response|\Illuminate\Http\RedirectResponse)  $next
     * @return \Illuminate\Http\Response|\Illuminate\Http\RedirectResponse
     */
    public function handle(Request $request, Closure $next)
    {
        $user = User::where('name', $request->get('shop'))->first();
        $scopes_resp = $user->api()->rest('GET', '/admin/oauth/access_scopes.json');

        if ($scopes_resp["errors"]) {
            return $next($request);
        }

        $scopes = $scopes_resp["body"]["access_scopes"];
        $scopes = json_decode(json_encode($scopes));
        $scopes = array_map(function($scope) {
            return $scope->handle;
        }, $scopes);
        $required_scopes = explode(',', env('SHOPIFY_API_SCOPES'));

        if (empty(array_diff($scopes, $required_scopes)) && empty(array_diff($required_scopes, $scopes))) {
            return $next($request);
        }

        Log::debug("SHOULD REDIRECT TO AUTH");

        return redirect()->route(
            Util::getShopifyConfig('route_names.authenticate'),
            [
                'shop' => $user->name,
                'host' => $request->get('host')
            ]
        );
    }
}

```
