### ISSUE TITLE
Shopify Admin domain issue

### ISSUE THREAD

**Issue by bagify** [Kyon147/laravel-shopify#89]
Shopify updates all stores' admin URLs to admin.shopify.com and now apps show notices with a new tab option. 

The app loaded but open a new tab and give notice. Check the attached screenshot.
![2023-02-09_18-23](https://user-images.githubusercontent.com/101622693/217824660-3a427222-99a1-48e1-be6f-43f274526a1d.png)

Check: https://changelog.shopify.com/posts/shopify-admin-now-lives-at-admin-shopify-com

**Comment by Lotuashvili** [comment]
+1, my app got rejected on that domain issue as well.

<img width="504" alt="image" src="https://user-images.githubusercontent.com/6238393/217940628-9b3ad536-c4de-4af3-bffe-75e687eb587f.png">

**Comment by Kyon147** [comment]
This is a known bug with the app bridge team, you can read more about it here https://github.com/Shopify/shopify-app-bridge/issues/160#issuecomment-1418205889

You also need to be on the latest version of the package as there have been updates to how we load in the host param that is needed.
