### ISSUE TITLE
App uninstall Webhook is not working on AWS

### ISSUE THREAD

**Issue by a-akashsoni** [Kyon147/laravel-shopify#90]
I have created app uninstall webhook in my package and placed code on AWS , but it did not work on AWS. It did not add anything in Laravel log file.
Please check the screenshot: https://prnt.sc/cIsQYr1sbc4d

Kindly give your reference on this issue as soon as possible.

Thanks

**Comment by Kyon147** [comment]
@a-akashsoni I have not tested the package on AWS so would not be able to give you any advice on this error.

I do have apps running fine on GCP and the set up is not going to be that different. The webhooks don't use anything super complex to run as they are just payloads sent to a URL.

The error you see looks like your webhook is not passing the middleware check which uses the HMAC for verification. Shopify [have more detail](https://shopify.dev/docs/apps/webhooks/configuration/https#step-5-verify-the-webhook) on how this works but the middleware should handle this for you. 

You probably need to do some more debugging to see why they are not being verified properly, as I say it is working fine for me on GCP but could not comment on AWS.

Post your question in the Discord, as someone else might be using AWS and can help you better.
