### ISSUE TITLE
Session token invalid

### ISSUE THREAD

**Issue by a-akashsoni** [Kyon147/laravel-shopify#93]
I have used the osiset laravel package to create the shopify app. I have placed the package in a folder on root folder. Now app is installed but laravel routes gives error invalid session token.

Please check the screenshot : https://prnt.sc/6Vz6AqYbZxQP

Kindly give your reference as soon as possible.

Thanks

**Comment by sahilcrawlapps** [comment]
Can you tell me the version of package and Laravel ?

**Comment by a-akashsoni** [comment]
Package version is 16 and Laravel package version is 7.

Thanks

**Comment by Kyon147** [comment]
As this is an older version I am closing this out, as you need to upgrade.
