### ISSUE TITLE
Unable to verify signature after Billing

### ISSUE THREAD

**Issue by SergejSi** [Kyon147/laravel-shopify#94]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

I get the error message every time after the payment process has gone through. 

update: 

After refreshing multiple times resp. going back  to the app dashboard and routes back to the shop it seems to work 

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create plan

RECURRING	Monthly	15.00	NULL	NULL	7	false	true	NULL	NULL	EVERY_30_DAYS

2. Make Billing on install

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v17.3
* Laravel Version: v9.19
* PHP Version: v8.0.2
* Template Engine: Blade

### Failure Logs

<img width="1118" alt="Bildschirm­foto 2023-02-16 um 13 32 33" src="https://user-images.githubusercontent.com/19937663/219366584-9c1e460e-47d5-4170-8a75-f6620058eee7.png">

**Comment by SergejSi** [comment]
Error is gone after installing the version 17.4.3

**Comment by Kyon147** [comment]
Closing as looks solved.
