### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by emtiazzahid** [Kyon147/laravel-shopify#96]
Need support for laravel 10 installation

```
 Problem 1
    - Root composer.json requires kyon147/laravel-shopify ^17.4 -> satisfiable by kyon147/laravel-shopify[v17.4.0, ..., v17.4.4].
    - kyon147/laravel-shopify[v17.4.0, ..., v17.4.4] require laravel/framework ^7.0 || ^8.0 || ^9.0 -> found laravel/framework[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but it conflicts with your root composer.json require (^10.0).
```

**Comment by vincenzoraco** [comment]
I've created a PR, awaiting for @Kyon147 to review it https://github.com/Kyon147/laravel-shopify/pull/97

**Comment by Kyon147** [comment]
Before I took over the package, I was looking at making 8.1 the minimum requirement due to an issue on `mixed` return type that the shopify-api package uses. 

It looks like this is one of the issues, so I will need to probably create a major release and make php 8.1 a requirement moving forward.

**Comment by sahilcrawlapps** [comment]
@Kyon147 I have a question is there any problem to use this package with PHP 8.1 or 8.2 versions ?
Because I am planning to make my new project on PHP 8.2,

**Comment by Kyon147** [comment]
@sp-artisan 8.1 should work fine for now as we are using a certain version of the api package that works with the current combination.

**Comment by alimud1** [comment]
@Kyon147 
When Laravel 10 will be added into package ? included php 8.2 support

**Comment by Kyon147** [comment]
@alimud1 there is an open PR for it at the moment but no specific release yet.

**Comment by alimud1** [comment]
Yes it but its not test and quality insurance

**Comment by zeeshanhaider6236dev** [comment]
Can you please update Laravel 10 in Main Repo ? after checking security test ?

**Comment by Kyon147** [comment]
Laravel 10 is on the list of things to do, there is no set date yet but I will try to get it sorted as quickly as my free time allows.

I'm going to lock this thread now for the time being.

**Comment by Kyon147** [comment]
Support for laravel 10 is part of v18 https://github.com/Kyon147/laravel-shopify/releases/tag/v18.0.0

Please read the update guide.
